# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Status.create(description: 'Active')
Status.create(description: 'Archived')
Status.create(description: 'Manually Archived')

Category.create(description: 'Art')
Category.create(description: 'Comics')
Category.create(description: 'Dance')
Category.create(description: 'Design')
Category.create(description: 'Fashion')
Category.create(description: 'Film & Video')
Category.create(description: 'Food')
Category.create(description: 'Games')
Category.create(description: 'Music')
Category.create(description: 'Photography')
Category.create(description: 'Publishing')
Category.create(description: 'Technology')
Category.create(description: 'Theater')
Category.create(description: 'Unidentified')

Subcategory.create(description: 'Conceptual Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Crafts', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Digital Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Illustration', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Painting', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Performance Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Mixed Media', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Public Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Sculpture', category_id: Category.find_by_description('Art').id)

Subcategory.create(description: 'Graphic Design', category_id: Category.find_by_description('Design').id)
Subcategory.create(description: 'Product Design', category_id: Category.find_by_description('Design').id)

Subcategory.create(description: 'Animation', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Documentary', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Narrative Film', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Short Film', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Webseries', category_id: Category.find_by_description('Film & Video').id)

Subcategory.create(description: 'Tabletop Games', category_id: Category.find_by_description('Games').id)
Subcategory.create(description: 'Video Games', category_id: Category.find_by_description('Games').id)

Subcategory.create(description: 'Classical Music', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Country & Folk', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Electronic Music', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Hip-Hop', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Indie Rock', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Jazz', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Pop', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Rock', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'World Music', category_id: Category.find_by_description('Music').id)

Subcategory.create(description: 'Art Book', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Children' 's Book', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Fiction', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Journalism', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Nonfiction', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Periodical', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Poetry', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Radio & Podcast', category_id: Category.find_by_description('Publishing').id)

Subcategory.create(description: 'Hardware', category_id: Category.find_by_description('Technology').id)
Subcategory.create(description: 'Open Software', category_id: Category.find_by_description('Technology').id)

s = Status.find_by_description('Active')





c = Category.find_by_description('Music')





p = Project.create(goal: 17490, kick_id: 'aharburg/gregorian-chant-modes-album', project_link: 'http://www.kickstarter.com/projects/aharburg/gregorian-chant-modes-album', category_id: c.id, name: 'Gregorian Chant Modes Album', start_date: '19.08.2013', expiration_date: '23.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/590648/photo-main.jpg?1376555560', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/590648/video-279450-h264_high.mp4', description: 'An album featuring an interpretation of the 8 Roman chant modes for those new to Chant.')
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.01.2014', description: 'Exclusive updates and get a shout out on Twitter! ')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.01.2014', description: 'A track download, updates and Twitter shout out. ')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.01.2014', description: 'Download the entire album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.01.2014', description: 'Hard copy of the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.02.2014', description: 'Hard copy of the album with rewards from lower tiers. This is for INTERNATIONAL backers. ')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.01.2014', description: 'A signed print of the mini-poster with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: 'Signed copy of the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.02.2014', description: 'Signed copy of the album with rewards from lower tiers. For INTERNATIONAL backers. ')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.01.2014', description: '"Special Thanks" credit on the album and invitation to the CD release party in Detroit (you are responsible for your own transportation) with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.02.2014', description: 'Invitation to visit during one of the recording sessions and meet the artists along with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.02.2014', description: '"Executive Producer" credit on the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.02.2014', description: 'A personalized workshop with you, Wassim, and up to 25 musicians of your choice. All participants will receive signed copies of the CD along with the mini-poster. ')
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 3, amount_pledged: 70)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 10, amount_pledged: 330)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 18, amount_pledged: 590)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 45, amount_pledged: 1407)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 10000, kick_id: '654131116/frederic-records-his-debut-album-and-films-music-v', project_link: 'http://www.kickstarter.com/projects/654131116/frederic-records-his-debut-album-and-films-music-v', category_id: c.id, name: 'Frederic Records His Debut Album & Films Music Video!!', start_date: '19.08.2013', expiration_date: '16.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/648984/photo-main.jpg?1376605843', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/648984/video-279082-h264_high.mp4', description: 'Following my demo, this is my first album & music video! It isn''t possible without your help so thank you so much for your support!')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.09.2013', description: 'A personal tweet shout-out and facebook shout-out. Make sure to follow me on twitter and like my facebook fan page. Thank You!!')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.11.2013', description: 'Personal tweet & facebook shout-out as well as a digital copy of the album when released.')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.11.2013', description: 'Personal tweet & facebook shout-out, a digital copy of the album when released, and a personal shout-out on one of my blog videos.')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.11.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, and handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture.')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.11.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, and your name in the credits on my album.')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.12.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, your name in the credits on my album, and an appearance in my first music video/being on set for the filming.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, your name in the credits on my album, an appearance in my first music video/being on set for the filming, and a dinner date in Hollywood.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.12.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, your name in the credits on my album, an appearance in my first music video/being on set for the filming, a dinner date in Hollywood, and the opportunity to sit in at the studio for 1 studio session and see how the recording and mixing goes down.')
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 1, amount_pledged: 15)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 5, amount_pledged: 145)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 8, amount_pledged: 473)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 9, amount_pledged: 632)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 12000, kick_id: '1075125090/full-devil-jacket-2nd-album-release', project_link: 'http://www.kickstarter.com/projects/1075125090/full-devil-jacket-2nd-album-release', category_id: c.id, name: 'Full Devil Jacket 2nd Album Release', start_date: '21.08.2013', expiration_date: '20.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/651093/photo-main.jpg?1377113631', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/651093/video-279523-h264_high.mp4"', description: 'Full Devil Jacket Is releasing their first record in over 12 yrs and we want you to be a part of it!')
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.10.2013', description: 'Thank you in weekly blog video')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.11.2013', description: '(1) First single digital download "1 week before release date" or at the end of the kick starter project. (1) Personalized autographed picture of the band, and your name in the album credits. (also $1 reward)')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.01.2014', description: '(1) Signed copy of the EP by the band "1 week before release date". (5) Full Devil Jacket Picks (also $1 and $10 rewards)')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.01.2014', description: '(1) Full Devil Jacket limited adition Kick Starter t-shirt. (also $1, $10, and $25 reward)')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: '(1) Signed hand written lyrics by Josh Brown of ANY FDJ song of your choosing. (1) Signed drum stick from Keith Foster. (also $1, $10, $25 and $50 rewards)')
Pledge.create(project_id: p.id, min_amount: 150, delivery_date: '01.01.2014', description: '(1) Grill out with the band. You and a one friend can come hang and grill out with the band AND get to hear the new record first hand with a live show. Must be able to travel to us (travel and lodging expenses are not included in the reward). (also $1, $10, $25, $50 and $100 rewards)')
Pledge.create(project_id: p.id, min_amount: 200, delivery_date: '01.01.2014', description: '(1) Skype session with the band while they are in the studio recording the album. (also $1, $10, $25, $50, $100 and $150 rewards)')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.01.2014', description: '1) Signed drumhead that was used during the recording of the record by all the members in the band. (also $1, $10, $25, $50, $100, $150 and $200 rewards)')
Pledge.create(project_id: p.id, min_amount: 350, delivery_date: '01.01.2014', description: '(1) sit in on a rehearsal or recording session with the band and bring (1) one friend. (also $1, $10, $25, $50, $100, $150, $200 and $250 rewards)')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.01.2014', description: '(1) VIP Package - you and a friend come to any FDJ show of your choice. Watch a sound check and hang with the band backstage before and after the show. All lodging and travel expenses are not covered by reward but we have a cool tree house you can stay in if you are down with that sort of thing.(also $1, $10, $25, $50, $100, $150, $200, $250 and $350 rewards)')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.01.2014', description: '(1) Fender guitar signed by all the band members. (also $1, $10, $25, $50, $100, $150, $200, $250, $350 and $500 rewards)')
Pledge.create(project_id: p.id, min_amount: 1500, delivery_date: '01.01.2014', description: '(1) your very own writing session with Josh Brown. Sit in the studio and have a writing session with the lead singer of Full Devil Jacket. OH, and did we mention his song writing has won some major awards? Well we just did. (also $1, $10, $25, $50, $100, $150, $200, $250, $300, $500 and $1000 rewards)')
Pledge.create(project_id: p.id, min_amount: 2000, delivery_date: '01.01.2014', description: '(1) tattoo session with Josh Brown and yes it is permanent. (also $1, $10, $25, $50, $100, $150, $200, $250, $300, $500, $1000 and $1500 rewards)')
Pledge.create(project_id: p.id, min_amount: 3000, delivery_date: '01.01.2014', description: '(1) Personal acoustic show at your house, backyard, garage, wherever as long as it''s a well lit place and your not crazy. PA for acoustic not needed. You also get to name one song off the record and it will stay this way for the track listing once the new record is complete. Must be within 400 miles of Nashville, TN. If over 400 miles gas, meals and hotel would have to be provided. Email us in interested and we will work out what we need to, if over 400 miles. (also $1.00, $10.00, $25.00, $50.00 rewards)')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.01.2014', description: '(1) Gig at acceptable venue of choice. You or the venue must provide acceptable PA and meed FDJ rider requirements. (We have a list of what you/venue would need so please ask if not sure), must also be within 600 miles of Nashville, TN. Also, you get to come on stage for your favorite song to sing or play with band. Anything over 600 miles please contact us for info for what we need to travel over 600 miles. (also $1.00, $10.00, $25.00, $50.00 rewards)')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.01.2014', description: 'Grab the exclusive position and become our executive producer for the new album. 1) Full Devil Jacket Membership VIP pass to any of our shows in 2014 as long as 2 weeks notice of you coming to the show is given. Also, all the prizes listed above except only 1 of the 2 rewards $3000.00 and $5000.00. May only choose 1 of the 2 for this reward.')
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 3, amount_pledged: 134)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 15, amount_pledged: 740)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 5000, kick_id: 'reesegalido/new-reese-galido-record', project_link: 'http://www.kickstarter.com/projects/reesegalido/new-reese-galido-record?ref=category', category_id: c.id, name: 'NEW Reese Galido RECORD', start_date: '21.08.2013', expiration_date: '20.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/607825/photo-main.jpg?1372818083', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/607825/video-280109-h264_high.mp4', description: 'Californian singer / songwriter Reese Galido records on the Central Coast at the iconic Painted Sky Studios')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.02.2014', description: 'THE BITS - Get a pre-release digital download of the album and enjoy with your ear parts!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.02.2014', description: 'COMPACT "LASER" DISC - Please enjoy a signed physical copy of the CD, shoot "Light Amplified by Stimulated Emission of Radiation", sit back, and enjoy. (+) DIGITAL DOWNLOAD')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.12.2013', description: 'KAZOO - Bust some mind blowing kazoo solos on your official Reese Galido kazoo. Now go out and make some beautiful music you crazy dreamer! (+) DIGITAL DOWNLOAD, SIGNED CD')
Pledge.create(project_id: p.id, min_amount: 30, delivery_date: '01.12.2013', description: 'COLD BEVERAGES - Ensconce your frosty deliciousness in an official Reese Galido pint glass. Guaranteed to make your drink room temperature if left unattended! (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 45, delivery_date: '01.02.2014', description: 'THE THREADS - Your torso is so lonely without a Reese Galido T-shirt to keep it company. Let''s give them a happy reunion (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 65, delivery_date: '01.02.2014', description: 'A ROSE BY ANY OTHER NAME - You may be known by many names, but yours will be featured in the liner notes of the album with my eternal thanks! (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 85, delivery_date: '01.02.2014', description: 'LIVE AND IN CONCERT - When we release the CD into the wild, I want you to be there. Grab 2 tickets to the CD release party and celebrate music with me. (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 175, delivery_date: '01.02.2014', description: 'ANY REQUESTS? - The song of your choice performed by yours truly and uploaded to YouTube where it will live on the interwebs forever! (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.02.2014', description: 'THE TRAVELING BARD - (California only or you provide transport) Reese will come and play a set at your dinner party or lunch party, or your brunch party (no breakfast party because that just sounds too early). (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 350, delivery_date: '01.02.2014', description: 'I AM WONDER MIC - and I''d like to say hello. Get tickets to the CD release party and sing a song with Reese. What song? Your choice. (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.02.2014', description: 'SONGWRITER / SINGER - Reese will compose a custom song for you based on the theme of your choice and upload a performance of the song to YouTube. Heck, she''s even written a song about rice before so sky''s the limit! (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 850, delivery_date: '01.02.2014', description: 'I AM! YOUR SINGING TELEGRAM :) - (California only or you provide transport) Send the Reesie to your loved one''s home or place of work with a love song and we''ll get it on camera! (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.02.2014', description: '')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.02.2014', description: '')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.02.2014', description: '')
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 3, amount_pledged: 74)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 10, amount_pledged: 436)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





c = Category.find_by_description('Games')





p = Project.create(goal: 400000, kick_id: 'playnery/mother-of-myth-phenomenal-multi-platform-action-rp', project_link: 'd', category_id: c.id, name: 'Mother of Myth - Phenomenal Multi-platform Action RPG', start_date: '12.08.2013', expiration_date: '14.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/600588/photo-main.jpg?1375618255', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/600588/video-278890-h264_high.mp4', description: 'Mother of Myth is a high-quality social action role-playing game developed for smartphones, tablets and web browsers.')
Pledge.create(project_id: p.id, min_amount: 1, description: 'THANKS FOR YOUR SUPPORT! ============================= Tirones ============================= All tiers include our sincere thanks in credits on our website, access to backers only forum. We appreciate your support! =============================', delivery_date: '01.11.2013')
Pledge.create(project_id: p.id, min_amount: 7, description: 'Munifex ============================= You will have the access to our beta in September 2013! This tier also includes an exclusive set of stickers. The digital rewards will be delivered to you by November 2013. =============================', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 15, description: 'Discens ============================= You will have the access to our beta in September 2013! This tier also includes a special deity skill card created for our backers, downloadable soundtrack, exclusive set of stickers and button badge.', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 25, description: 'Immunes ============================= Everything from the Discens tier + Wings of Glory, decoration wings that NO one else will have in Mother of Myth + Downloadable Script Book + Game Art Postcards.', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 50, description: 'Optio ============================= Everything from the Immunes tier + Downloadable Art Book + EARLY BIRD Special Redeem Code (Value $10.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 100, description: 'Primus Pilus ============================= Everything from the Optio tier + Exclusive Print Poster + Special Credits On Game Prop + EARLY BIRD Special Redeem Code (Value $20.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 500, description: 'Praefectus ============================= Everything from the Primus Pilus tier + Exclusive T-Shirt + Printed Script Book or Art Book (SELECT ONE) + EARLY BIRD Special Redeem Code (Value $75.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 1000, description: 'Tribunes ============================= Everything from the Praefectus tier + Printed Script Book AND Art Book + Heart-felt Credits In Game + EARLY BIRD Special Redeem Code (Value $100.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 5000, description: 'Tribunus Laticlavius ============================= Everything from the Tribunes tier + Exclusive Game Figure + Name a Deity Card and a Dungeon', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 10000, description: 'Legatus Legionis ============================= Everything from the Tribunus Laticlavius tier + Associate Producer Credit In Game + Invitation for our private party for 2 persons (Excluding the flights / We cover a hotel room for 1 night)', delivery_date: '01.01.2014')
dat = PushDate.create(push_date: '12.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 2, amount_pledged: 70)
dat = PushDate.create(push_date: '13.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 10, amount_pledged: 470)
dat = PushDate.create(push_date: '14.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 23, amount_pledged: 1015)
dat = PushDate.create(push_date: '15.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 42, amount_pledged: 1463)
dat = PushDate.create(push_date: '16.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 60, amount_pledged: 2317)
dat = PushDate.create(push_date: '17.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 75, amount_pledged: 2947)
dat = PushDate.create(push_date: '18.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 104, amount_pledged: 3713)
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 113, amount_pledged: 4036)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 129, amount_pledged: 6347)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 139, amount_pledged: 9874)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 148, amount_pledged: 12605)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 115000, kick_id: 'u55/u55-end-of-the-line', project_link: 'http://www.kickstarter.com/projects/u55/u55-end-of-the-line', category_id: c.id, name: 'U55 - END OF THE LINE', start_date: '20.08.2013', expiration_date: '19.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/649035/photo-main.jpg?1376416663', video_link: 'https://www.youtube.com/watch?v=muSjOGxBJOg', description: 'Deeply embedded in H.P. Lovecrafts mythology, U55 – END OF THE LINE is an innovative horror game set in modern-day Berlin.')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.12.2014', description: 'SIZE "XXS" BRONZE Your name is mentioned in the credits, you will get access to the developer forum and you get the Backer Badge in bronze (A cool mobile wallpaper with your name on it) ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.12.2014', description: 'SIZE "XS" BRONZE EARLY BIRD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.12.2014', description: 'SIZE "XS" BRONZE Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE ')
Pledge.create(project_id: p.id, min_amount: 37, delivery_date: '01.12.2014', description: 'SIZE "S" BRONZE EARLY BIRD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE / Digital HR Artwork / Digital Soundtrack / Digital Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.12.2014', description: 'SIZE "S" BRONZE Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE / Digital HR Artwork / Digital Soundtrack / Digital Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary')
Pledge.create(project_id: p.id, min_amount: 75, delivery_date: '01.12.2014', description: 'SIZE "M" SILVER Your name is mentioned in the credits / Access to the developer forum / Backer Badge in silver (your name) / Boxed Copy of U55 - END OF THE LINE / Digital HR Artwork / Digital Soundtrack / Digital Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.12.2014', description: 'SIZE "L" SILVER Your name is mentioned in the credits / Access to the developer forum / Backer Badge in silver (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary / U55 Sticker / Making-Of DVD')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.12.2014', description: 'SIZE "XL" GOLD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2014', description: 'SIZE "XXL" GOLD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / PLUS Your company''s poster in game / Creative Talk with Malte')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2014', description: 'SIZE "XXL" GOLD SPECIAL EDITION Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / PLUS Your company''s poster in game / Creative Talk with Malte / PLUS CREATE AN ITEM FOR U55')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.12.2014', description: 'SIZE "3XL" PLATINUM Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / PLUS ASSOCIATE PRODUCER CREDIT')
Pledge.create(project_id: p.id, min_amount: 2500, delivery_date: '01.12.2014', description: 'SIZE "4XL" PLATINUM LIMITED Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / Associate Producer Credit / PLUS Party with the Team in Berlin (you pay flight, we hotel and drinks)')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.12.2014', description: 'SIZE "5XL" PLATINUM LIMITED Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / Associate Producer Credit / PLUS Party with the Team in Berlin (you pay flight, we hotel and drinks) / PLUS Creative Visit on site at U55 and create an NPC')
Pledge.create(project_id: p.id, min_amount: 7500, delivery_date: '01.12.2014', description: 'SIZE "6XL" PLATINUM LIMITED Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / Associate Producer Credit / PLUS Party with the Team in Berlin (you pay flight, we hotel and drinks) / PLUS Creative Visit on site at U55 PLUS create and VOICEACT an NPC')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.12.2014', description: 'SIZE "Holy Cow!" PLATINUM UNIQUE Everything from the "6XL" PLATINUM Tier + YOU get to create the backstory for our Main Character (Only a few limits are there: Male, English Speaking, that''s it...) This is the biggest gift you can give someone. Make him (or YOU) the star of U55 - END OF THE LINE')
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 14, amount_pledged: 985)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 97, amount_pledged: 4567)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 221, amount_pledged: 10415)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 7000, kick_id: '1604325867/stronghold-2d-multiplayer-mobile-game', project_link: 'http://www.kickstarter.com/projects/1604325867/stronghold-2d-multiplayer-mobile-game', category_id: c.id, name: 'Stronghold 2D - Mass Multiplayer Mobile War Game', start_date: '19.08.2013', expiration_date: '18.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/600613/photo-main.jpg?1377049295', video_link: 'https://www.youtube.com/watch?v=pXowKVDup0A', description: 'Angry Birds/Worms/Red Alert type of Multiplayer game for iPhone, iPad, and all Android Devices. Build a stronghold and protect it!')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.10.2013', description: 'Thank you for pledging! All pledges are rewarded with the Free Full Multiplayer Game, but you''ll also get: $5,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'You''ll get access the PRE-BETA game right when it comes out (same hour)! $12,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.10.2013', description: 'Get the Android app for free and get your name in BOLD in the credits of the game AND website. You''ll also get: $30,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.10.2013', description: 'Awesome Pledge! Your name will be included in the game credits! You''ll also get: $80,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.10.2013', description: 'Wow! Serious Pledge! This will include a very special thank you on the game credits (top) and website credits. You''ll also get: $200,000 In Game! **NEW** Name your own random citizen in game, change the color pants, gender, maybe even add a hat! (Users will be able to see name in-game) Once you populate your Stronghold, citizen will be wondering around!')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.10.2013', description: 'Awesome Pledge, You will be included on our game credits and website credits. You can include a small image and the name you want. You''ll also get: $500,000 In Game! AND All game objects for your battle!')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.10.2013', description: 'Tell us what you''d like in the game and I''ll make it and dedicate it to you! Anything from buildings, missiles, anything you can think of! Your name also gets to be on the top of the credits on your own line. You''ll also get: $1,000,000 In Game! AND All game objects for your battle! AND you get to name your own game object and the functions that it will do! Set the price too!')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.10.2013', description: 'Geesh, You''re one dedicated person, so we have to dedicate an important spot on the very top of the credits for you. You can include your name, web url, and an image. You''ll also get an unlimited amount of money In Game! AND All game objects for your battle! AND you get to name 3 of your own game object and the functions that it will do! Set the price too!')
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 1, amount_pledged: 15)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 4, amount_pledged: 43)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 5, amount_pledged: 94)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 10, amount_pledged: 176)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 125000, kick_id: 'ronimo/awesomenauts-starstorm', project_link: 'http://www.kickstarter.com/projects/ronimo/awesomenauts-starstorm', category_id: c.id, name: 'Awesomenauts: Starstorm', start_date: '19.08.2013', expiration_date: '18.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/595650/photo-main.jpg?1374593946', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/595650/video-280570-h264_high.mp4', description: 'We want to take Awesomenauts to the next level, with characters, features, a new map, and more! Join us to make this happen!')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.10.2013', description: 'WOOD TIER: 2 DIGITAL WALLPAPERS ------------------------ Once the Kickstarer campaign ends, we''ll send you a bunch of really cool Awesomenauts Wallpapers! Your desktop has never looked quite so... splendid!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'COPPER TIER: STARSTORM DLC + AWESOMENAUTS GAME KEY + DIGITAL SOUNDTRACK + 2 DIGITAL WALLPAPERS --------------------------- You''ll receive an access code for Awesomenauts: Starstorm on Steam when it launches. Once this campaign is completed, you''ll receive a digital copy of the soundtrack, a key for the Awesomenauts base game, and the Awesomenauts: Starstorm wallpapers from the Wood Tier!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'COPPER SKIN PACK 1 TIER: STARSTORM DLC + COSTUME PACK 1 KEY + DIGITAL SOUNDTRACK + 2 DIGITAL WALLPAPERS ------------------ You''ll receive an access code for Awesomenauts: Starstorm on Steam when it launches. Once this campaign is completed, you''ll receive a digital copy of the soundtrack, a Steam key for Costume Pack 1 (containing 9 skins), and the Awesomenauts: Starstorm wallpapers from the Wood Tier!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'COPPER SKIN PACK 2 TIER: STARSTORM DLC + COSTUME PACK 2 KEY + DIGITAL SOUNDTRACK + 2 DIGITAL WALLPAPERS ------------------ You''ll receive an access code for Awesomenauts: Starstorm on Steam when it launches. Once this campaign is completed, you''ll receive a digital copy of the soundtrack, a Steam key for Costume Pack 2 (containing 9 skins), and the Awesomenauts: Starstorm wallpapers from the Wood Tier!')
Pledge.create(project_id: p.id, min_amount: 30, delivery_date: '01.10.2013', description: 'IRON TIER: EARLY BETA ACCESS + ALL ITEMS FROM LOWER TIERS ---- In addition to everything included in the Copper tier, you''ll receive Beta access on Steam for all the new features and characters that we''ll release in Awesomenauts: Starstorm. Share your thoughts on the content we have in development!')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.12.2013', description: 'BRONZE TIER: GHOST LEON EXCLUSIVE SKIN + EXCLUSIVE ANNOUNCER + DIGITAL ARTBOOK + ALL ITEMS FROM LOWER TIERS ---- You''ll get all the rewards from the Iron Tier, and also receive an exclusive in-game skin for Leon on Steam, a new in-game announcer, and a digital artbook featuring concept art, random doodles, and awesome graphics!')
Pledge.create(project_id: p.id, min_amount: 75, delivery_date: '01.12.2013', description: 'SILVER TIER: STARSTORM POSTER + SILVER KILLER KOALA ICON + EXTRA GIFT COPIES OF STARSTORM DLC, GAME AND SOUNDTRACK + ALL ITEMS FROM LOWER TIERS ------------------------ Time to get physical! You''ll get all the things from the Bronze Tier, as well as an Awesomenauts: Starstorm poster delivered to your doorstep. You''ll also get an in-game Silver Killer Koala icon in the Steam version of the game, and an extra Steam copy of the base game, the Starstorm expansion, and our killer soundtrack!')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: 'GOLD TIER: AWESOMENAUTS T-SHIRT + MENTION IN SPECIAL THANKS IN CREDITS + ALL ITEMS FROM LOWER TIERS -------------- Show the world how awesome you are! All the rewards from the Silver Tier are included and you''ll receive one of three mind-blowing Awesomenauts t-shirts (your pick). You will also be mentioned in the Special Thanks section of the Awesomenauts credits!')
Pledge.create(project_id: p.id, min_amount: 160, delivery_date: '01.01.2014', description: 'THORIUM TIER: A BOT NAMED AFTER YOU + ALL THREE T-SHIRTS + ALL ITEMS FROM LOWER TIERS --- In addition to the rewards from the Silver Tier, you get to name an in-game bot after whatever you like (within reason, of course), and receive not only one, but ALL THREE of the Super Awesome Awesomenauts T-Shirts!')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.02.2014', description: 'PLUTONIUM CLUNK TIER: CLUNK FIGURINE + GOLDEN KILLER KOALA ICON + ALL ITEMS FROM THORIUM TIER --------------------------------------- You''ll get all the awesomeness from the Thorium Tier, we''ll give you a Golden Killer Koala icon in-game, and we''ll send you a kick-ass Clunk figurine! Nothing says love like 4" of pure destruction!')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.02.2014', description: 'PLUTONIUM VINYL TIER: SIGNED SOUNDTRACK VINYL + GOLDEN KILLER KOALA ICON + ALL ITEMS FROM THORIUM TIER -------------- You''ll get all of the awesomeness from the Thorium Thier, we''ll give you one of those Golden Killer Koala in-game icons in the Steam version of the game, and send you a real 12" Awesomenauts record with the soundtrack. We''ll also get the entire team to sign it, for good measure! Nothing says love like 12" of black vinyl!')
Pledge.create(project_id: p.id, min_amount: 450, delivery_date: '01.02.2014', description: 'AWESOMANTIUM TIER: SIGNED SOUNDTRACK VINYL + CLUNK FIGURINE + GOLDEN KILLER KOALA ICON + MENTION IN VERY AWESOME THANKS IN CREDITS + MENTION IN DROP-POD AREA IN EVERY MAP + ALL ITEMS FROM THORIUM TIER ---- You''ll get everything we''ve talked about so far. That means you get both the 4" Clunk figurine and the ridiculously cool Awesomenauts Soundtrack record. The record sleeve will carry the autographs of all the people on our team! We will also mention you in the Very Awesome Thanks section of the Awesomenauts credits, and put your name in a small in-game shrine that shows up in the dropzone of all maps.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.02.2014', description: 'ZURIAN OVERLORD TIER: NAME AN IN-GAME ITEM + ALL ITEMS FROM AWESOMANTIUM TIER ------------------ Let me start off by saying that we love you! You will be allowed to come up with the name and flavour text for one of the items of the new characters! Time to write your own Awesomenauts history! You will also get everything from the Awesomantium Tier.')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.04.2014', description: 'ZORK INDUSTRIES VIP: YOUR STATUE IN A MAP + ALL ITEMS FROM ZURIAN OVERLORD TIER ----- In proper Blabl Zork-fashion, you can get your own statue in one of the maps of the game. You get to decide what you want the statue to be (within reason)! You''ll also get a truckload of goodies: everything included in the Zurian Overlord Tier!')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.04.2014', description: 'CAKEMANTIUM TIER: DESIGN YOUR OWN SKIN + VOICE YOUR OWN SKIN + VISIT RONIMO + GET CAKE + ALL ITEMS FROM ZORK INDUSTRIES VIP TIER --------------------------------------- You get everything we''ve talked about up to this point, and get to design your own character skin (with a custom voice). You''ll get Steam keys to give the skin to all your friends and you''re the only one who will ever be allowed to distribute this exclusive skin. Also, you''re welcome to join the development team for a day at our office in Utrecht, play all the stuff we have in development, talk to whoever you like on our team about whatever you like. We''ll make it a fun day, and our producer will personally bake you a cake (you''ll have to pay for the travel arrangements and your stay in Utrecht yourself, though)!')
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 126, amount_pledged: 5437)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 657, amount_pledged: 24679)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 947, amount_pledged: 47679)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 1562, amount_pledged: 82990)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 55000, kick_id: 'kermdinger/stunt-runner-a-hilarious-new-take-on-physics-puzzl', project_link: 'http://www.kickstarter.com/projects/kermdinger/stunt-runner-a-hilarious-new-take-on-physics-puzzl', category_id: c.id, name: 'Stunt Runner - A Hilarious New Take on Physics Puzzlers', start_date: '05.08.2013', expiration_date: '04.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/622758/photo-main.jpg?1375692932', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/622758/video-275159-h264_high.mp4', description: 'Lemmings meets The Incredible Machine gameplay. Help stunt actor Smash Johnson make his epic comeback to the big screen!')
Pledge.create(project_id: p.id, min_amount: 12, delivery_date: '01.01.2014', description: '**********EARLY BIRD SPECIAL********** - “IT’S NOT A TOOMAH!” - Digital download of the game, access to backer-only video updates, and a special in-game credit as an early bird backer.')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.01.2014', description: '- “MY PRECIOUS.” - Digital download of the game, access to backer-only video updates, and an in-game credit as a backer.')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.01.2014', description: '- “VERY NICE, HOW MUCH?” Special edition of the game which contains a PDF version of the Stunt Runner Art Bible (concept art and a detailed look at our art pipeline), two digital wallpapers, a DRM-free copy of the game’s soundtrack, a cover photo for Facebook, and all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 30, delivery_date: '01.01.2014', description: '**********EARLY BIRD SPECIAL********** - “''IF YOU AIN''T FIRST, YOU''RE LAST.''” - Get ALL FUTURE DIGITAL CONTENT FREE FOR LIFE that we make post-launch for Stunt Runner (levels, costumes, props -- any DLC), a special in-game credit as an early bird backer, plus all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 35, delivery_date: '01.01.2014', description: '- “YOU’RE GONNA NEED A BIGGER BOAT.” - Get ALL FUTURE DIGITAL CONTENT FREE FOR LIFE that we make post-launch for Stunt Runner (levels, costumes, props -- any DLC), plus all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 45, delivery_date: '01.11.2013', description: '- “I’LL HAVE WHAT SHE’S HAVING.” - Get exclusive access to the Beta version of Stunt Runner and the ability to give us valuable feedback during the game’s development to shape our design! Plus, get an extra game key to give Stunt Runner to a friend, and all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 60, delivery_date: '01.11.2013', description: '- “INCONCEIVABLE!” - Get physical with your choice of a black or white Stunt Runner Kickstarter T-Shirt and all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: '- “HE LOOKS LIKE A PINK NIGHTMARE.” - KICKSTARTER EXCLUSIVE CONTENT - Get a special in-game pink bunny suit and a goofy hat that can ONLY be acquired by backing this tier or higher in our Kickstarter campaign, plus all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 300, delivery_date: '01.03.2014', description: '- “THAT BELONGS IN A MUSEUM.” - A glorious piece of Stunt Runner art ONLY available to backers in this tier -- digitally hand-painted, printed on canvas and wrapped around a solid wood box backing for hanging, signed by the development team, plus all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 400, delivery_date: '01.03.2014', description: '- “SO DO YOU.” - Get a 5” tall 3D printed figurine of Smash Johnson with the base signed by the development team, plus all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.10.2013', description: '- “I KNOW KUNG FU.” - Work with us to design an official level for our game and see your work featured in a shipped title! These levels will be part of the full game and will have your name on them as the designer. You’ll be credited as a “Kickstarter Level Designer” to be used for your resume or portfolio! You’ll also receive all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.01.2014', description: '- “SO YOU’RE TELLING ME THERE’S A CHANCE.” - Come join us at our launch party in San Francisco (travel not included), get four special edition copies of the game (on top of the one received at the $30 tier), and you’ll receive an “Associate Producer” credit with the option to participate in monthly Skype chats to help shape development. You’ll also receive all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 2500, delivery_date: '01.01.2014', description: '-”I SHALL CALL HIM...MINI-ME.”- We’ll model a stylized version of YOU and insert you as a character in Stunt Runner! Your character can have your name, your favorite gamer handle or a nickname (within reason of course). We’ll also record your voice for your character and credit you as an Actor in Stunt Runner. Come join us at our launch party in San Francisco (travel not included), and get 4 special edition copies of the game (on top of the one received at the $30 tier) as well as all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.03.2014', description: '- “I’VE A FEELING WE’RE NOT IN KANSAS ANYMORE.” - Spend the weekend with us in San Francisco! Sightseeing in the city, surfing lessons and more! We’ll pay for two nights at the W Hotel, but you will be responsible for all flights to and from San Francisco. You’ll be credited as a Producer in Stunt Runner, and you’ll also receive four special edition copies of the game (on top of the one received at the $30 tier) and all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.01.2014', description: '- “MADE IT MA! TOP OF THE WORLD!” This is it! You are completely onboard with our vision for Stunt Runner! We will be attending a variety of trade shows to promote the game, and we would like YOU to join us. We will pay the price of your attendance, room, and board (airfare not included) at any show that we attend (minimum of three). Help us show off the game, hang out with other developers, and get a better idea of what our world is like. You’ll receive an “Executive Producer” credit, four special edition copies of the game (on top of the one received at the $30 tier) and all previous non-limited reward tiers. You will also receive a crown made of paper mache and tears of joy!')
dat = PushDate.create(push_date: '05.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 2, amount_pledged: 15)
dat = PushDate.create(push_date: '06.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 18, amount_pledged: 94)
dat = PushDate.create(push_date: '07.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 47, amount_pledged: 256)
dat = PushDate.create(push_date: '08.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 52, amount_pledged: 400)
dat = PushDate.create(push_date: '09.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 60, amount_pledged: 509)
dat = PushDate.create(push_date: '10.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 71, amount_pledged: 734)
dat = PushDate.create(push_date: '11.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 85, amount_pledged: 806)
dat = PushDate.create(push_date: '12.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 87, amount_pledged: 1258)
dat = PushDate.create(push_date: '13.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 89, amount_pledged: 1434)
dat = PushDate.create(push_date: '14.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 99, amount_pledged: 1945)
dat = PushDate.create(push_date: '15.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 101, amount_pledged: 2431)
dat = PushDate.create(push_date: '16.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 117, amount_pledged: 2945)
dat = PushDate.create(push_date: '17.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 124, amount_pledged: 3015)
dat = PushDate.create(push_date: '18.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 135, amount_pledged: 3415)
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 140, amount_pledged: 3947)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 159, amount_pledged: 4319)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 162, amount_pledged: 4579)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 170, amount_pledged: 4663)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)





p = Project.create(goal: 7000, kick_id: '', project_link: '', category_id: c.id, name: '', start_date: '19.08.2013', expiration_date: '18.09.2013', status_id: s.id, picture_link: '', video_link: '', description: '')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.12.2014', description: '')
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 111, amount_pledged: 111)
dat = PushDate.create(push_date: '23.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '24.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '25.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '26.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '27.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)
dat = PushDate.create(push_date: '28.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 0, amount_pledged: 0)