# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Status.create(description: 'Active')
Status.create(description: 'Archived')
Status.create(description: 'Manually Archived')

Category.create(description: 'Art')
Category.create(description: 'Comics')
Category.create(description: 'Dance')
Category.create(description: 'Design')
Category.create(description: 'Fashion')
Category.create(description: 'Film & Video')
Category.create(description: 'Food')
Category.create(description: 'Games')
Category.create(description: 'Music')
Category.create(description: 'Photography')
Category.create(description: 'Publishing')
Category.create(description: 'Technology')
Category.create(description: 'Theater')
Category.create(description: 'Unidentified')

Subcategory.create(description: 'Conceptual Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Crafts', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Digital Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Illustration', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Painting', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Performance Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Mixed Media', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Public Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Sculpture', category_id: Category.find_by_description('Art').id)

Subcategory.create(description: 'Graphic Design', category_id: Category.find_by_description('Design').id)
Subcategory.create(description: 'Product Design', category_id: Category.find_by_description('Design').id)

Subcategory.create(description: 'Animation', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Documentary', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Narrative Film', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Short Film', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Webseries', category_id: Category.find_by_description('Film & Video').id)

Subcategory.create(description: 'Tabletop Games', category_id: Category.find_by_description('Games').id)
Subcategory.create(description: 'Video Games', category_id: Category.find_by_description('Games').id)

Subcategory.create(description: 'Classical Music', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Country & Folk', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Electronic Music', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Hip-Hop', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Indie Rock', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Jazz', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Pop', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Rock', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'World Music', category_id: Category.find_by_description('Music').id)

Subcategory.create(description: 'Art Book', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Children' 's Book', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Fiction', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Journalism', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Nonfiction', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Periodical', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Poetry', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Radio & Podcast', category_id: Category.find_by_description('Publishing').id)

Subcategory.create(description: 'Hardware', category_id: Category.find_by_description('Technology').id)
Subcategory.create(description: 'Open Software', category_id: Category.find_by_description('Technology').id)

c = Category.find_by_description('Games')
s = Status.find_by_description('Active')
p = Project.create(goal: 400000, kick_id: 'playnery/mother-of-myth-phenomenal-multi-platform-action-rp', project_link: 'http://www.kickstarter.com/projects/playnery/mother-of-myth-phenomenal-multi-platform-action-rp?ref=category', category_id: c.id, name: 'Mother of Myth - Phenomenal Multi-platform Action RPG', start_date: '12.08.2013', expiration_date: '14.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/600588/photo-main.jpg?1375618255', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/600588/video-278890-h264_high.mp4', description: 'Mother of Myth is a high-quality social action role-playing game developed for smartphones, tablets and web browsers.')
Pledge.create(project_id: p.id, min_amount: 1, description: 'THANKS FOR YOUR SUPPORT! ============================= Tirones ============================= All tiers include our sincere thanks in credits on our website, access to backers only forum. We appreciate your support! =============================', delivery_date: '01.11.2013')
Pledge.create(project_id: p.id, min_amount: 7, description: 'Munifex ============================= You will have the access to our beta in September 2013! This tier also includes an exclusive set of stickers. The digital rewards will be delivered to you by November 2013. =============================', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 15, description: 'Discens ============================= You will have the access to our beta in September 2013! This tier also includes a special deity skill card created for our backers, downloadable soundtrack, exclusive set of stickers and button badge.', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 25, description: 'Immunes ============================= Everything from the Discens tier + Wings of Glory, decoration wings that NO one else will have in Mother of Myth + Downloadable Script Book + Game Art Postcards.', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 50, description: 'Optio ============================= Everything from the Immunes tier + Downloadable Art Book + EARLY BIRD Special Redeem Code (Value $10.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 100, description: 'Primus Pilus ============================= Everything from the Optio tier + Exclusive Print Poster + Special Credits On Game Prop + EARLY BIRD Special Redeem Code (Value $20.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 500, description: 'Praefectus ============================= Everything from the Primus Pilus tier + Exclusive T-Shirt + Printed Script Book or Art Book (SELECT ONE) + EARLY BIRD Special Redeem Code (Value $75.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 1000, description: 'Tribunes ============================= Everything from the Praefectus tier + Printed Script Book AND Art Book + Heart-felt Credits In Game + EARLY BIRD Special Redeem Code (Value $100.00) ', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 5000, description: 'Tribunus Laticlavius ============================= Everything from the Tribunes tier + Exclusive Game Figure + Name a Deity Card and a Dungeon', delivery_date: '01.01.2014')
Pledge.create(project_id: p.id, min_amount: 10000, description: 'Legatus Legionis ============================= Everything from the Tribunus Laticlavius tier + Associate Producer Credit In Game + Invitation for our private party for 2 persons (Excluding the flights / We cover a hotel room for 1 night)', delivery_date: '01.01.2014')

dat = PushDate.create(push_date: '12.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 2, amount_pledged: 70)
dat = PushDate.create(push_date: '13.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 10, amount_pledged: 470)
dat = PushDate.create(push_date: '14.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 23, amount_pledged: 1015)
dat = PushDate.create(push_date: '15.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 42, amount_pledged: 1463)
dat = PushDate.create(push_date: '16.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 60, amount_pledged: 2317)
dat = PushDate.create(push_date: '17.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 75, amount_pledged: 2947)
dat = PushDate.create(push_date: '18.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 104, amount_pledged: 3713)
dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 113, amount_pledged: 4036)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 129, amount_pledged: 4469)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 139, amount_pledged: 4736)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 154, amount_pledged: 5234)


c = Category.find_by_description('Music')
s = Status.find_by_description('Active')
p = Project.create(goal: 17490, kick_id: 'aharburg/gregorian-chant-modes-album', project_link: 'http://www.kickstarter.com/projects/aharburg/gregorian-chant-modes-album?ref=category', category_id: c.id, name: 'Gregorian Chant Modes Album', start_date: '19.08.2013', expiration_date: '23.09.2013', status_id: s.id, picture_link: 'https://s3.amazonaws.com/ksr/projects/590648/photo-main.jpg?1376555560', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/590648/video-279450-h264_high.mp4', description: 'An album featuring an interpretation of the 8 Roman chant modes for those new to Chant.')
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.01.2014', description: 'Exclusive updates and get a shout out on Twitter! ')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.01.2014', description: 'A track download, updates and Twitter shout out. ')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.01.2014', description: 'Download the entire album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.01.2014', description: 'Hard copy of the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.02.2014', description: 'Hard copy of the album with rewards from lower tiers. This is for INTERNATIONAL backers. ')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.01.2014', description: 'A signed print of the mini-poster with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: 'Signed copy of the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.02.2014', description: 'Signed copy of the album with rewards from lower tiers. For INTERNATIONAL backers. ')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.01.2014', description: '"Special Thanks" credit on the album and invitation to the CD release party in Detroit (you are responsible for your own transportation) with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.02.2014', description: 'Invitation to visit during one of the recording sessions and meet the artists along with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.02.2014', description: '"Executive Producer" credit on the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.02.2014', description: 'A personalized workshop with you, Wassim, and up to 25 musicians of your choice. All participants will receive signed copies of the CD along with the mini-poster. ')

dat = PushDate.create(push_date: '19.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 3, amount_pledged: 70)
dat = PushDate.create(push_date: '20.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 10, amount_pledged: 330)
dat = PushDate.create(push_date: '21.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 18, amount_pledged: 590)
dat = PushDate.create(push_date: '22.08.2013')
Daily.create(project_id: p.id, push_date_id: dat.id, amount_backers: 47, amount_pledged: 1015)