Status.create(description: 'Active')
Status.create(description: 'Archived')
Status.create(description: 'Manually Archived')

Category.create(description: 'Art')
Category.create(description: 'Comics')
Category.create(description: 'Dance')
Category.create(description: 'Design')
Category.create(description: 'Fashion')
Category.create(description: 'Film & Video')
Category.create(description: 'Food')
Category.create(description: 'Games')
Category.create(description: 'Music')
Category.create(description: 'Photography')
Category.create(description: 'Publishing')
Category.create(description: 'Technology')
Category.create(description: 'Theater')
Category.create(description: 'Unidentified')

Subcategory.create(description: 'Conceptual Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Crafts', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Digital Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Illustration', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Painting', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Performance Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Mixed Media', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Public Art', category_id: Category.find_by_description('Art').id)
Subcategory.create(description: 'Sculpture', category_id: Category.find_by_description('Art').id)

Subcategory.create(description: 'Graphic Design', category_id: Category.find_by_description('Design').id)
Subcategory.create(description: 'Product Design', category_id: Category.find_by_description('Design').id)

Subcategory.create(description: 'Animation', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Documentary', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Narrative Film', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Short Film', category_id: Category.find_by_description('Film & Video').id)
Subcategory.create(description: 'Webseries', category_id: Category.find_by_description('Film & Video').id)

Subcategory.create(description: 'Tabletop Games', category_id: Category.find_by_description('Games').id)
Subcategory.create(description: 'Video Games', category_id: Category.find_by_description('Games').id)

Subcategory.create(description: 'Classical Music', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Country & Folk', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Electronic Music', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Hip-Hop', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Indie Rock', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Jazz', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Pop', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'Rock', category_id: Category.find_by_description('Music').id)
Subcategory.create(description: 'World Music', category_id: Category.find_by_description('Music').id)

Subcategory.create(description: 'Art Book', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Children' 's Book', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Fiction', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Journalism', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Nonfiction', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Periodical', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Poetry', category_id: Category.find_by_description('Publishing').id)
Subcategory.create(description: 'Radio & Podcast', category_id: Category.find_by_description('Publishing').id)

Subcategory.create(description: 'Hardware', category_id: Category.find_by_description('Technology').id)
Subcategory.create(description: 'Open Software', category_id: Category.find_by_description('Technology').id)

PushDate.create(push_date: '16.07.2013')
PushDate.create(push_date: '17.07.2013')
PushDate.create(push_date: '18.07.2013')
PushDate.create(push_date: '19.07.2013')
PushDate.create(push_date: '20.07.2013')
PushDate.create(push_date: '21.07.2013')
PushDate.create(push_date: '22.07.2013')
PushDate.create(push_date: '23.07.2013')
PushDate.create(push_date: '24.07.2013')
PushDate.create(push_date: '25.07.2013')
PushDate.create(push_date: '26.07.2013')
PushDate.create(push_date: '27.07.2013')
PushDate.create(push_date: '28.07.2013')
PushDate.create(push_date: '29.07.2013')
PushDate.create(push_date: '30.07.2013')
PushDate.create(push_date: '31.07.2013')
PushDate.create(push_date: '01.08.2013')
PushDate.create(push_date: '02.08.2013')
PushDate.create(push_date: '03.08.2013')
PushDate.create(push_date: '04.08.2013')
PushDate.create(push_date: '05.08.2013')
PushDate.create(push_date: '06.08.2013')
PushDate.create(push_date: '07.08.2013')
PushDate.create(push_date: '08.08.2013')
PushDate.create(push_date: '09.08.2013')
PushDate.create(push_date: '10.08.2013')
PushDate.create(push_date: '11.08.2013')
PushDate.create(push_date: '12.08.2013')
PushDate.create(push_date: '13.08.2013')
PushDate.create(push_date: '14.08.2013')
PushDate.create(push_date: '15.08.2013')
PushDate.create(push_date: '16.08.2013')
PushDate.create(push_date: '17.08.2013')
PushDate.create(push_date: '18.08.2013')
PushDate.create(push_date: '19.08.2013')
PushDate.create(push_date: '20.08.2013')
PushDate.create(push_date: '21.08.2013')
PushDate.create(push_date: '22.08.2013')
PushDate.create(push_date: '23.08.2013')
PushDate.create(push_date: '24.08.2013')
PushDate.create(push_date: '25.08.2013')
PushDate.create(push_date: '26.08.2013')
PushDate.create(push_date: '27.08.2013')
PushDate.create(push_date: '28.08.2013')





c = Category.find_by_description('Music')





p = Project.create(goal: 17490, start_date: '19.08.2013', expiration_date: '23.09.2013', kick_id: 'aharburg/gregorian-chant-modes-album', name: 'Gregorian Chant Modes Album', description: 'An album featuring an interpretation of the 8 Roman chant modes for those new to Chant.', project_link: 'http://www.kickstarter.com/projects/aharburg/gregorian-chant-modes-album', picture_link: 'https://s3.amazonaws.com/ksr/projects/590648/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/590648/video-279450-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.01.2014', description: 'Exclusive updates and get a shout out on Twitter! ')
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.01.2014', description: 'A track download, updates and Twitter shout out. ')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.01.2014', description: 'Download the entire album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.01.2014', description: 'Hard copy of the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.02.2014', description: 'Hard copy of the album with rewards from lower tiers. This is for INTERNATIONAL backers. ')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.01.2014', description: 'A signed print of the mini-poster with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: 'Signed copy of the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.02.2014', description: 'Signed copy of the album with rewards from lower tiers. For INTERNATIONAL backers. ')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.01.2014', description: '"Special Thanks" credit on the album and invitation to the CD release party in Detroit (you are responsible for your own transportation) with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.02.2014', description: 'Invitation to visit during one of the recording sessions and meet the artists along with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.02.2014', description: '"Executive Producer" credit on the album with rewards from lower tiers. ')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.02.2014', description: 'A personalized workshop with you, Wassim, and up to 25 musicians of your choice. All participants will receive signed copies of the CD along with the mini-poster. ')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 3, amount_pledged: 70)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 10, amount_pledged: 330)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 18, amount_pledged: 590)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 45, amount_pledged: 1407)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 53, amount_pledged: 1647)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 57, amount_pledged: 1698)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 59, amount_pledged: 1749)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 61, amount_pledged: 1843)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 72, amount_pledged: 2722)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 83, amount_pledged: 3158)





p = Project.create(goal: 10000, start_date: '19.08.2013', expiration_date: '16.09.2013', kick_id: '654131116/frederic-records-his-debut-album-and-films-music-v', name: 'Frederic Records His Debut Album & Films Music Video!!', description: 'Following my demo, this is my first album & music video! It isn''t possible without your help so thank you so much for your support!', project_link: 'http://www.kickstarter.com/projects/654131116/frederic-records-his-debut-album-and-films-music-v', picture_link: 'https://s3.amazonaws.com/ksr/projects/648984/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/648984/video-279082-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.09.2013', description: 'A personal tweet shout-out and facebook shout-out. Make sure to follow me on twitter and like my facebook fan page. Thank You!!')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.11.2013', description: 'Personal tweet & facebook shout-out as well as a digital copy of the album when released.')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.11.2013', description: 'Personal tweet & facebook shout-out, a digital copy of the album when released, and a personal shout-out on one of my blog videos.')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.11.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, and handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture.')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.11.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, and your name in the credits on my album.')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.12.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, your name in the credits on my album, and an appearance in my first music video/being on set for the filming.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, your name in the credits on my album, an appearance in my first music video/being on set for the filming, and a dinner date in Hollywood.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.12.2013', description: 'Personal tweet and facebook shout out, digital copy of the album when released, personal blog shout out, handwritten lyrics to your favorite "Frederic Gladney" song signed by me with a signed picture, your name in the credits on my album, an appearance in my first music video/being on set for the filming, a dinner date in Hollywood, and the opportunity to sit in at the studio for 1 studio session and see how the recording and mixing goes down.')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 1, amount_pledged: 15)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 5, amount_pledged: 145)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 8, amount_pledged: 473)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 9, amount_pledged: 632)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 9, amount_pledged: 632)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 9, amount_pledged: 632)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 10, amount_pledged: 642)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 10, amount_pledged: 642)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 10, amount_pledged: 642)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 11, amount_pledged: 657)





p = Project.create(goal: 12000, start_date: '21.08.2013', expiration_date: '20.09.2013', kick_id: '1075125090/full-devil-jacket-2nd-album-release', name: 'Full Devil Jacket 2nd Album Release', description: 'Full Devil Jacket Is releasing their first record in over 12 yrs and we want you to be a part of it!', project_link: 'http://www.kickstarter.com/projects/1075125090/full-devil-jacket-2nd-album-release', picture_link: 'https://s3.amazonaws.com/ksr/projects/651093/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/651093/video-279523-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.10.2013', description: 'Thank you in weekly blog video')
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.11.2013', description: '(1) First single digital download "1 week before release date" or at the end of the kick starter project. (1) Personalized autographed picture of the band, and your name in the album credits. (also $1 reward)')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.01.2014', description: '(1) Signed copy of the EP by the band "1 week before release date". (5) Full Devil Jacket Picks (also $1 and $10 rewards)')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.01.2014', description: '(1) Full Devil Jacket limited adition Kick Starter t-shirt. (also $1, $10, and $25 reward)')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: '(1) Signed hand written lyrics by Josh Brown of ANY FDJ song of your choosing. (1) Signed drum stick from Keith Foster. (also $1, $10, $25 and $50 rewards)')
Pledge.create(project_id: p.id, min_amount: 150, delivery_date: '01.01.2014', description: '(1) Grill out with the band. You and a one friend can come hang and grill out with the band AND get to hear the new record first hand with a live show. Must be able to travel to us (travel and lodging expenses are not included in the reward). (also $1, $10, $25, $50 and $100 rewards)')
Pledge.create(project_id: p.id, min_amount: 200, delivery_date: '01.01.2014', description: '(1) Skype session with the band while they are in the studio recording the album. (also $1, $10, $25, $50, $100 and $150 rewards)')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.01.2014', description: '(1) Signed drumhead that was used during the recording of the record by all the members in the band. (also $1, $10, $25, $50, $100, $150 and $200 rewards)')
Pledge.create(project_id: p.id, min_amount: 350, delivery_date: '01.01.2014', description: '(1) sit in on a rehearsal or recording session with the band and bring (1) one friend. (also $1, $10, $25, $50, $100, $150, $200 and $250 rewards)')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.01.2014', description: '(1) VIP Package - you and a friend come to any FDJ show of your choice. Watch a sound check and hang with the band backstage before and after the show. All lodging and travel expenses are not covered by reward but we have a cool tree house you can stay in if you are down with that sort of thing.(also $1, $10, $25, $50, $100, $150, $200, $250 and $350 rewards)')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.01.2014', description: '(1) Fender guitar signed by all the band members. (also $1, $10, $25, $50, $100, $150, $200, $250, $350 and $500 rewards)')
Pledge.create(project_id: p.id, min_amount: 1500, delivery_date: '01.01.2014', description: '(1) your very own writing session with Josh Brown. Sit in the studio and have a writing session with the lead singer of Full Devil Jacket. OH, and did we mention his song writing has won some major awards? Well we just did. (also $1, $10, $25, $50, $100, $150, $200, $250, $300, $500 and $1000 rewards)')
Pledge.create(project_id: p.id, min_amount: 2000, delivery_date: '01.01.2014', description: '(1) tattoo session with Josh Brown and yes it is permanent. (also $1, $10, $25, $50, $100, $150, $200, $250, $300, $500, $1000 and $1500 rewards)')
Pledge.create(project_id: p.id, min_amount: 3000, delivery_date: '01.01.2014', description: '(1) Personal acoustic show at your house, backyard, garage, wherever as long as it''s a well lit place and your not crazy. PA for acoustic not needed. You also get to name one song off the record and it will stay this way for the track listing once the new record is complete. Must be within 400 miles of Nashville, TN. If over 400 miles gas, meals and hotel would have to be provided. Email us in interested and we will work out what we need to, if over 400 miles. (also $1.00, $10.00, $25.00, $50.00 rewards)')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.01.2014', description: '(1) Gig at acceptable venue of choice. You or the venue must provide acceptable PA and meed FDJ rider requirements. (We have a list of what you/venue would need so please ask if not sure), must also be within 600 miles of Nashville, TN. Also, you get to come on stage for your favorite song to sing or play with band. Anything over 600 miles please contact us for info for what we need to travel over 600 miles. (also $1.00, $10.00, $25.00, $50.00 rewards)')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.01.2014', description: 'Grab the exclusive position and become our executive producer for the new album. 1) Full Devil Jacket Membership VIP pass to any of our shows in 2014 as long as 2 weeks notice of you coming to the show is given. Also, all the prizes listed above except only 1 of the 2 rewards $3000.00 and $5000.00. May only choose 1 of the 2 for this reward.')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 3, amount_pledged: 134)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 15, amount_pledged: 740)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 18, amount_pledged: 805)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 21, amount_pledged: 1156)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 24, amount_pledged: 1467)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 28, amount_pledged: 1750)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 32, amount_pledged: 2060)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 37, amount_pledged: 2467)





p = Project.create(goal: 5000, start_date: '21.08.2013', expiration_date: '20.09.2013', kick_id: 'reesegalido/new-reese-galido-record', name: 'NEW Reese Galido RECORD', description: 'Californian singer / songwriter Reese Galido records on the Central Coast at the iconic Painted Sky Studios', project_link: 'http://www.kickstarter.com/projects/reesegalido/new-reese-galido-record', picture_link: 'https://s3.amazonaws.com/ksr/projects/607825/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/607825/video-280109-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 10, delivery_date: '01.02.2014', description: 'THE BITS - Get a pre-release digital download of the album and enjoy with your ear parts!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.02.2014', description: 'COMPACT "LASER" DISC - Please enjoy a signed physical copy of the CD, shoot "Light Amplified by Stimulated Emission of Radiation", sit back, and enjoy. (+) DIGITAL DOWNLOAD')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.12.2013', description: 'KAZOO - Bust some mind blowing kazoo solos on your official Reese Galido kazoo. Now go out and make some beautiful music you crazy dreamer! (+) DIGITAL DOWNLOAD, SIGNED CD')
Pledge.create(project_id: p.id, min_amount: 30, delivery_date: '01.12.2013', description: 'COLD BEVERAGES - Ensconce your frosty deliciousness in an official Reese Galido pint glass. Guaranteed to make your drink room temperature if left unattended! (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 45, delivery_date: '01.02.2014', description: 'THE THREADS - Your torso is so lonely without a Reese Galido T-shirt to keep it company. Let''s give them a happy reunion (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 65, delivery_date: '01.02.2014', description: 'A ROSE BY ANY OTHER NAME - You may be known by many names, but yours will be featured in the liner notes of the album with my eternal thanks! (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 85, delivery_date: '01.02.2014', description: 'LIVE AND IN CONCERT - When we release the CD into the wild, I want you to be there. Grab 2 tickets to the CD release party and celebrate music with me. (+) DIGITAL DOWNLOAD, SIGNED CD, KAZOO')
Pledge.create(project_id: p.id, min_amount: 175, delivery_date: '01.02.2014', description: 'ANY REQUESTS? - The song of your choice performed by yours truly and uploaded to YouTube where it will live on the interwebs forever! (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.02.2014', description: 'THE TRAVELING BARD - (California only or you provide transport) Reese will come and play a set at your dinner party or lunch party, or your brunch party (no breakfast party because that just sounds too early). (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 350, delivery_date: '01.02.2014', description: 'I AM WONDER MIC - and I''d like to say hello. Get tickets to the CD release party and sing a song with Reese. What song? Your choice. (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.02.2014', description: 'SONGWRITER / SINGER - Reese will compose a custom song for you based on the theme of your choice and upload a performance of the song to YouTube. Heck, she''s even written a song about rice before so sky''s the limit! (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Pledge.create(project_id: p.id, min_amount: 850, delivery_date: '01.02.2014', description: 'I AM! YOUR SINGING TELEGRAM :) - (California only or you provide transport) Send the Reesie to your loved one''s home or place of work with a love song and we''ll get it on camera! (+) DIGITAL DOWNLOAD, SIGNED CD, T-SHIRT, KAZOO, PINT GLASS, YOUR NAME IN THE LINER NOTES, TICKETS TO THE RELEASE')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 3, amount_pledged: 74)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 10, amount_pledged: 436)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 11, amount_pledged: 450)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 13, amount_pledged: 576)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 15, amount_pledged: 769)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 18, amount_pledged: 1013)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 18, amount_pledged: 1013)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 18, amount_pledged: 1013)





c = Category.find_by_description('Games')





p = Project.create(goal: 400000, start_date: '12.08.2013', expiration_date: '14.09.2013', kick_id: 'playnery/mother-of-myth-phenomenal-multi-platform-action-rp', name: 'Mother of Myth - Phenomenal Multi-platform Action RPG', description: 'Mother of Myth is a high-quality social action role-playing game developed for smartphones, tablets and web browsers.', project_link: 'http://www.kickstarter.com/projects/playnery/mother-of-myth-phenomenal-multi-platform-action-rp', picture_link: 'https://s3.amazonaws.com/ksr/projects/600588/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/600588/video-278890-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.11.2013', description: 'THANKS FOR YOUR SUPPORT! ============================= Tirones ============================= All tiers include our sincere thanks in credits on our website, access to backers only forum. We appreciate your support! =============================')
Pledge.create(project_id: p.id, min_amount: 7, delivery_date: '01.01.2014', description: 'Munifex ============================= You will have the access to our beta in September 2013! This tier also includes an exclusive set of stickers. The digital rewards will be delivered to you by November 2013. =============================')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.01.2014', description: 'Discens ============================= You will have the access to our beta in September 2013! This tier also includes a special deity skill card created for our backers, downloadable soundtrack, exclusive set of stickers and button badge.')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.01.2014', description: 'Immunes ============================= Everything from the Discens tier + Wings of Glory, decoration wings that NO one else will have in Mother of Myth + Downloadable Script Book + Game Art Postcards.')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.01.2014', description: 'Optio ============================= Everything from the Immunes tier + Downloadable Art Book + EARLY BIRD Special Redeem Code (Value $10.00) ')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: 'Primus Pilus ============================= Everything from the Optio tier + Exclusive Print Poster + Special Credits On Game Prop + EARLY BIRD Special Redeem Code (Value $20.00) ')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.01.2014', description: 'Praefectus ============================= Everything from the Primus Pilus tier + Exclusive T-Shirt + Printed Script Book or Art Book (SELECT ONE) + EARLY BIRD Special Redeem Code (Value $75.00) ')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.01.2014', description: 'Tribunes ============================= Everything from the Praefectus tier + Printed Script Book AND Art Book + Heart-felt Credits In Game + EARLY BIRD Special Redeem Code (Value $100.00) ')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.01.2014', description: 'Tribunus Laticlavius ============================= Everything from the Tribunes tier + Exclusive Game Figure + Name a Deity Card and a Dungeon')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.01.2014', description: 'Legatus Legionis ============================= Everything from the Tribunus Laticlavius tier + Associate Producer Credit In Game + Invitation for our private party for 2 persons (Excluding the flights / We cover a hotel room for 1 night)')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-12').id, amount_backers: 2, amount_pledged: 70)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-13').id, amount_backers: 10, amount_pledged: 470)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-14').id, amount_backers: 23, amount_pledged: 1015)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-15').id, amount_backers: 42, amount_pledged: 1463)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-16').id, amount_backers: 60, amount_pledged: 2317)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-17').id, amount_backers: 75, amount_pledged: 2947)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-18').id, amount_backers: 104, amount_pledged: 3713)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 113, amount_pledged: 4036)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 129, amount_pledged: 6347)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 139, amount_pledged: 9874)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 148, amount_pledged: 12605)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 149, amount_pledged: 12864)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 149, amount_pledged: 12864)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 150, amount_pledged: 12914)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 150, amount_pledged: 12914)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 152, amount_pledged: 12916)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 153, amount_pledged: 12921)





p = Project.create(goal: 115000, start_date: '20.09.2013', expiration_date: '19.09.2013', kick_id: 'u55/u55-end-of-the-line', name: 'U55 - END OF THE LINE', description: 'Deeply embedded in H.P. Lovecrafts mythology, U55 – END OF THE LINE is an innovative horror game set in modern-day Berlin.', project_link: 'http://www.kickstarter.com/projects/u55/u55-end-of-the-line', picture_link: 'https://s3.amazonaws.com/ksr/projects/649035/photo-main.jpg', video_link: 'https://www.youtube.com/watch?v=muSjOGxBJOg', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.12.2014', description: 'SIZE "XXS" BRONZE Your name is mentioned in the credits, you will get access to the developer forum and you get the Backer Badge in bronze (A cool mobile wallpaper with your name on it) ')
Pledge.create(project_id: p.id, min_amount: 20, delivery_date: '01.12.2014', description: 'SIZE "XS" BRONZE EARLY BIRD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.12.2014', description: 'SIZE "XS" BRONZE Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE ')
Pledge.create(project_id: p.id, min_amount: 37, delivery_date: '01.12.2014', description: 'SIZE "S" BRONZE EARLY BIRD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE / Digital HR Artwork / Digital Soundtrack / Digital Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.12.2014', description: 'SIZE "S" BRONZE Your name is mentioned in the credits / Access to the developer forum / Backer Badge in bronze (your name) / Digital Copy of U55 - END OF THE LINE / Digital HR Artwork / Digital Soundtrack / Digital Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary')
Pledge.create(project_id: p.id, min_amount: 75, delivery_date: '01.12.2014', description: 'SIZE "M" SILVER Your name is mentioned in the credits / Access to the developer forum / Backer Badge in silver (your name) / Boxed Copy of U55 - END OF THE LINE / Digital HR Artwork / Digital Soundtrack / Digital Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.12.2014', description: 'SIZE "L" SILVER Your name is mentioned in the credits / Access to the developer forum / Backer Badge in silver (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Digital SS & NKWD Documents / Digital Lena''s Diary / U55 Sticker / Making-Of DVD')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.12.2014', description: 'SIZE "XL" GOLD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2014', description: 'SIZE "XXL" GOLD Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / PLUS Your company''s poster in game / Creative Talk with Malte')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2014', description: 'SIZE "XXL" GOLD SPECIAL EDITION Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / PLUS Your company''s poster in game / Creative Talk with Malte / PLUS CREATE AN ITEM FOR U55')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.12.2014', description: 'SIZE "3XL" PLATINUM Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / PLUS ASSOCIATE PRODUCER CREDIT')
Pledge.create(project_id: p.id, min_amount: 2500, delivery_date: '01.12.2014', description: 'SIZE "4XL" PLATINUM LIMITED Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / Associate Producer Credit / PLUS Party with the Team in Berlin (you pay flight, we hotel and drinks)')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.12.2014', description: 'SIZE "5XL" PLATINUM LIMITED Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / Associate Producer Credit / PLUS Party with the Team in Berlin (you pay flight, we hotel and drinks) / PLUS Creative Visit on site at U55 and create an NPC')
Pledge.create(project_id: p.id, min_amount: 7500, delivery_date: '01.12.2014', description: 'SIZE "6XL" PLATINUM LIMITED Your name is mentioned in the credits / Access to the developer forum / Backer Badge in gold (your name) / Boxed Copy of U55 - END OF THE LINE / Printed HR Artwork / Soundtrack on CD / Printed Artbook / Printed SS & NKWD Documents / Printed Lena''s Diary / U55 Sticker / Making-Of DVD / U55 Safety Helmet / Berlin Subway Ticket/ Signed Poster / Your company''s poster in game / Creative Talk with Malte / Create an Item / Associate Producer Credit / PLUS Party with the Team in Berlin (you pay flight, we hotel and drinks) / PLUS Creative Visit on site at U55 PLUS create and VOICEACT an NPC')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.12.2014', description: 'SIZE "Holy Cow!" PLATINUM UNIQUE Everything from the "6XL" PLATINUM Tier + YOU get to create the backstory for our Main Character (Only a few limits are there: Male, English Speaking, that''s it...) This is the biggest gift you can give someone. Make him (or YOU) the star of U55 - END OF THE LINE')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 14, amount_pledged: 985)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 97, amount_pledged: 4567)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 221, amount_pledged: 10415)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 296, amount_pledged: 23075)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 315, amount_pledged: 24687)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 347, amount_pledged: 25376)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 453, amount_pledged: 29718)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 504, amount_pledged: 31290)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 567, amount_pledged: 33578)





p = Project.create(goal: 7000, start_date: '19.08.2013', expiration_date: '18.09.2013', kick_id: '1604325867/stronghold-2d-multiplayer-mobile-game', name: 'Stronghold 2D - Mass Multiplayer Mobile War Game', description: 'Angry Birds/Worms/Red Alert type of Multiplayer game for iPhone, iPad, and all Android Devices. Build a stronghold and protect it!', project_link: 'http://www.kickstarter.com/projects/1604325867/stronghold-2d-multiplayer-mobile-game', picture_link: 'https://s3.amazonaws.com/ksr/projects/600613/photo-main.jpg', video_link: 'https://www.youtube.com/watch?v=pXowKVDup0A', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.10.2013', description: 'Thank you for pledging! All pledges are rewarded with the Free Full Multiplayer Game, but you''ll also get: $5,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'You''ll get access the PRE-BETA game right when it comes out (same hour)! $12,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.10.2013', description: 'Get the Android app for free and get your name in BOLD in the credits of the game AND website. You''ll also get: $30,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.10.2013', description: 'Awesome Pledge! Your name will be included in the game credits! You''ll also get: $80,000 In Game!')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.10.2013', description: 'Wow! Serious Pledge! This will include a very special thank you on the game credits (top) and website credits. You''ll also get: $200,000 In Game! **NEW** Name your own random citizen in game, change the color pants, gender, maybe even add a hat! (Users will be able to see name in-game) Once you populate your Stronghold, citizen will be wondering around!')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.10.2013', description: 'Awesome Pledge, You will be included on our game credits and website credits. You can include a small image and the name you want. You''ll also get: $500,000 In Game! AND All game objects for your battle!')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.10.2013', description: 'Tell us what you''d like in the game and I''ll make it and dedicate it to you! Anything from buildings, missiles, anything you can think of! Your name also gets to be on the top of the credits on your own line. You''ll also get: $1,000,000 In Game! AND All game objects for your battle! AND you get to name your own game object and the functions that it will do! Set the price too!')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.10.2013', description: 'Geesh, You''re one dedicated person, so we have to dedicate an important spot on the very top of the credits for you. You can include your name, web url, and an image. You''ll also get an unlimited amount of money In Game! AND All game objects for your battle! AND you get to name 3 of your own game object and the functions that it will do! Set the price too!')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 1, amount_pledged: 15)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 4, amount_pledged: 43)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 5, amount_pledged: 94)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 10, amount_pledged: 176)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 26, amount_pledged: 5392)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 32, amount_pledged: 5469)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 39, amount_pledged: 5679)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 44, amount_pledged: 5877)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 47, amount_pledged: 5922)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 50, amount_pledged: 6011)





p = Project.create(goal: 125000, start_date: '19.08.2013', expiration_date: '18.09.2013', kick_id: 'ronimo/awesomenauts-starstorm', name: 'Awesomenauts: Starstorm', description: 'We want to take Awesomenauts to the next level, with characters, features, a new map, and more! Join us to make this happen!', project_link: 'http://www.kickstarter.com/projects/ronimo/awesomenauts-starstorm', picture_link: 'https://s3.amazonaws.com/ksr/projects/595650/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/595650/video-280570-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.10.2013', description: 'WOOD TIER: 2 DIGITAL WALLPAPERS ------------------------ Once the Kickstarer campaign ends, we''ll send you a bunch of really cool Awesomenauts Wallpapers! Your desktop has never looked quite so... splendid!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'COPPER TIER: STARSTORM DLC + AWESOMENAUTS GAME KEY + DIGITAL SOUNDTRACK + 2 DIGITAL WALLPAPERS --------------------------- You''ll receive an access code for Awesomenauts: Starstorm on Steam when it launches. Once this campaign is completed, you''ll receive a digital copy of the soundtrack, a key for the Awesomenauts base game, and the Awesomenauts: Starstorm wallpapers from the Wood Tier!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'COPPER SKIN PACK 1 TIER: STARSTORM DLC + COSTUME PACK 1 KEY + DIGITAL SOUNDTRACK + 2 DIGITAL WALLPAPERS ------------------ You''ll receive an access code for Awesomenauts: Starstorm on Steam when it launches. Once this campaign is completed, you''ll receive a digital copy of the soundtrack, a Steam key for Costume Pack 1 (containing 9 skins), and the Awesomenauts: Starstorm wallpapers from the Wood Tier!')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.10.2013', description: 'COPPER SKIN PACK 2 TIER: STARSTORM DLC + COSTUME PACK 2 KEY + DIGITAL SOUNDTRACK + 2 DIGITAL WALLPAPERS ------------------ You''ll receive an access code for Awesomenauts: Starstorm on Steam when it launches. Once this campaign is completed, you''ll receive a digital copy of the soundtrack, a Steam key for Costume Pack 2 (containing 9 skins), and the Awesomenauts: Starstorm wallpapers from the Wood Tier!')
Pledge.create(project_id: p.id, min_amount: 30, delivery_date: '01.10.2013', description: 'IRON TIER: EARLY BETA ACCESS + ALL ITEMS FROM LOWER TIERS ---- In addition to everything included in the Copper tier, you''ll receive Beta access on Steam for all the new features and characters that we''ll release in Awesomenauts: Starstorm. Share your thoughts on the content we have in development!')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.12.2013', description: 'BRONZE TIER: GHOST LEON EXCLUSIVE SKIN + EXCLUSIVE ANNOUNCER + DIGITAL ARTBOOK + ALL ITEMS FROM LOWER TIERS ---- You''ll get all the rewards from the Iron Tier, and also receive an exclusive in-game skin for Leon on Steam, a new in-game announcer, and a digital artbook featuring concept art, random doodles, and awesome graphics!')
Pledge.create(project_id: p.id, min_amount: 75, delivery_date: '01.12.2013', description: 'SILVER TIER: STARSTORM POSTER + SILVER KILLER KOALA ICON + EXTRA GIFT COPIES OF STARSTORM DLC, GAME AND SOUNDTRACK + ALL ITEMS FROM LOWER TIERS ------------------------ Time to get physical! You''ll get all the things from the Bronze Tier, as well as an Awesomenauts: Starstorm poster delivered to your doorstep. You''ll also get an in-game Silver Killer Koala icon in the Steam version of the game, and an extra Steam copy of the base game, the Starstorm expansion, and our killer soundtrack!')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: 'GOLD TIER: AWESOMENAUTS T-SHIRT + MENTION IN SPECIAL THANKS IN CREDITS + ALL ITEMS FROM LOWER TIERS -------------- Show the world how awesome you are! All the rewards from the Silver Tier are included and you''ll receive one of three mind-blowing Awesomenauts t-shirts (your pick). You will also be mentioned in the Special Thanks section of the Awesomenauts credits!')
Pledge.create(project_id: p.id, min_amount: 160, delivery_date: '01.01.2014', description: 'THORIUM TIER: A BOT NAMED AFTER YOU + ALL THREE T-SHIRTS + ALL ITEMS FROM LOWER TIERS --- In addition to the rewards from the Silver Tier, you get to name an in-game bot after whatever you like (within reason, of course), and receive not only one, but ALL THREE of the Super Awesome Awesomenauts T-Shirts!')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.02.2014', description: 'PLUTONIUM CLUNK TIER: CLUNK FIGURINE + GOLDEN KILLER KOALA ICON + ALL ITEMS FROM THORIUM TIER --------------------------------------- You''ll get all the awesomeness from the Thorium Tier, we''ll give you a Golden Killer Koala icon in-game, and we''ll send you a kick-ass Clunk figurine! Nothing says love like 4" of pure destruction!')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.02.2014', description: 'PLUTONIUM VINYL TIER: SIGNED SOUNDTRACK VINYL + GOLDEN KILLER KOALA ICON + ALL ITEMS FROM THORIUM TIER -------------- You''ll get all of the awesomeness from the Thorium Thier, we''ll give you one of those Golden Killer Koala in-game icons in the Steam version of the game, and send you a real 12" Awesomenauts record with the soundtrack. We''ll also get the entire team to sign it, for good measure! Nothing says love like 12" of black vinyl!')
Pledge.create(project_id: p.id, min_amount: 450, delivery_date: '01.02.2014', description: 'AWESOMANTIUM TIER: SIGNED SOUNDTRACK VINYL + CLUNK FIGURINE + GOLDEN KILLER KOALA ICON + MENTION IN VERY AWESOME THANKS IN CREDITS + MENTION IN DROP-POD AREA IN EVERY MAP + ALL ITEMS FROM THORIUM TIER ---- You''ll get everything we''ve talked about so far. That means you get both the 4" Clunk figurine and the ridiculously cool Awesomenauts Soundtrack record. The record sleeve will carry the autographs of all the people on our team! We will also mention you in the Very Awesome Thanks section of the Awesomenauts credits, and put your name in a small in-game shrine that shows up in the dropzone of all maps.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.02.2014', description: 'ZURIAN OVERLORD TIER: NAME AN IN-GAME ITEM + ALL ITEMS FROM AWESOMANTIUM TIER ------------------ Let me start off by saying that we love you! You will be allowed to come up with the name and flavour text for one of the items of the new characters! Time to write your own Awesomenauts history! You will also get everything from the Awesomantium Tier.')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.04.2014', description: 'ZORK INDUSTRIES VIP: YOUR STATUE IN A MAP + ALL ITEMS FROM ZURIAN OVERLORD TIER ----- In proper Blabl Zork-fashion, you can get your own statue in one of the maps of the game. You get to decide what you want the statue to be (within reason)! You''ll also get a truckload of goodies: everything included in the Zurian Overlord Tier!')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.04.2014', description: 'CAKEMANTIUM TIER: DESIGN YOUR OWN SKIN + VOICE YOUR OWN SKIN + VISIT RONIMO + GET CAKE + ALL ITEMS FROM ZORK INDUSTRIES VIP TIER --------------------------------------- You get everything we''ve talked about up to this point, and get to design your own character skin (with a custom voice). You''ll get Steam keys to give the skin to all your friends and you''re the only one who will ever be allowed to distribute this exclusive skin. Also, you''re welcome to join the development team for a day at our office in Utrecht, play all the stuff we have in development, talk to whoever you like on our team about whatever you like. We''ll make it a fun day, and our producer will personally bake you a cake (you''ll have to pay for the travel arrangements and your stay in Utrecht yourself, though)!')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 126, amount_pledged: 5437)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 657, amount_pledged: 24679)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 947, amount_pledged: 47679)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 1562, amount_pledged: 82990)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 1862, amount_pledged: 97521)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 2167, amount_pledged: 108695)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 2469, amount_pledged: 124634)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 2695, amount_pledged: 133567)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 2914, amount_pledged: 141862)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 3312, amount_pledged: 149684)





p = Project.create(goal: 55000, start_date: '05.08.2013', expiration_date: '04.09.2013', kick_id: 'kermdinger/stunt-runner-a-hilarious-new-take-on-physics-puzzl', name: 'Stunt Runner - A Hilarious New Take on Physics Puzzlers', description: 'Lemmings meets The Incredible Machine gameplay. Help stunt actor Smash Johnson make his epic comeback to the big screen!', project_link: 'http://www.kickstarter.com/projects/kermdinger/stunt-runner-a-hilarious-new-take-on-physics-puzzl', picture_link: 'https://s3.amazonaws.com/ksr/projects/622758/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/622758/video-275159-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 12, delivery_date: '01.01.2014', description: '**********EARLY BIRD SPECIAL********** - “IT’S NOT A TOOMAH!” - Digital download of the game, access to backer-only video updates, and a special in-game credit as an early bird backer.')
Pledge.create(project_id: p.id, min_amount: 15, delivery_date: '01.01.2014', description: '- “MY PRECIOUS.” - Digital download of the game, access to backer-only video updates, and an in-game credit as a backer.')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.01.2014', description: '- “VERY NICE, HOW MUCH?” Special edition of the game which contains a PDF version of the Stunt Runner Art Bible (concept art and a detailed look at our art pipeline), two digital wallpapers, a DRM-free copy of the game’s soundtrack, a cover photo for Facebook, and all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 30, delivery_date: '01.01.2014', description: '**********EARLY BIRD SPECIAL********** - “''IF YOU AIN''T FIRST, YOU''RE LAST.''” - Get ALL FUTURE DIGITAL CONTENT FREE FOR LIFE that we make post-launch for Stunt Runner (levels, costumes, props -- any DLC), a special in-game credit as an early bird backer, plus all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 35, delivery_date: '01.01.2014', description: '- “YOU’RE GONNA NEED A BIGGER BOAT.” - Get ALL FUTURE DIGITAL CONTENT FREE FOR LIFE that we make post-launch for Stunt Runner (levels, costumes, props -- any DLC), plus all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 45, delivery_date: '01.11.2013', description: '- “I’LL HAVE WHAT SHE’S HAVING.” - Get exclusive access to the Beta version of Stunt Runner and the ability to give us valuable feedback during the game’s development to shape our design! Plus, get an extra game key to give Stunt Runner to a friend, and all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 60, delivery_date: '01.11.2013', description: '- “INCONCEIVABLE!” - Get physical with your choice of a black or white Stunt Runner Kickstarter T-Shirt and all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.01.2014', description: '- “HE LOOKS LIKE A PINK NIGHTMARE.” - KICKSTARTER EXCLUSIVE CONTENT - Get a special in-game pink bunny suit and a goofy hat that can ONLY be acquired by backing this tier or higher in our Kickstarter campaign, plus all previous reward tiers.')
Pledge.create(project_id: p.id, min_amount: 300, delivery_date: '01.03.2014', description: '- “THAT BELONGS IN A MUSEUM.” - A glorious piece of Stunt Runner art ONLY available to backers in this tier -- digitally hand-painted, printed on canvas and wrapped around a solid wood box backing for hanging, signed by the development team, plus all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 400, delivery_date: '01.03.2014', description: '- “SO DO YOU.” - Get a 5” tall 3D printed figurine of Smash Johnson with the base signed by the development team, plus all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.10.2013', description: '- “I KNOW KUNG FU.” - Work with us to design an official level for our game and see your work featured in a shipped title! These levels will be part of the full game and will have your name on them as the designer. You’ll be credited as a “Kickstarter Level Designer” to be used for your resume or portfolio! You’ll also receive all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.01.2014', description: '- “SO YOU’RE TELLING ME THERE’S A CHANCE.” - Come join us at our launch party in San Francisco (travel not included), get four special edition copies of the game (on top of the one received at the $30 tier), and you’ll receive an “Associate Producer” credit with the option to participate in monthly Skype chats to help shape development. You’ll also receive all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 2500, delivery_date: '01.01.2014', description: '-”I SHALL CALL HIM...MINI-ME.”- We’ll model a stylized version of YOU and insert you as a character in Stunt Runner! Your character can have your name, your favorite gamer handle or a nickname (within reason of course). We’ll also record your voice for your character and credit you as an Actor in Stunt Runner. Come join us at our launch party in San Francisco (travel not included), and get 4 special edition copies of the game (on top of the one received at the $30 tier) as well as all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 5000, delivery_date: '01.03.2014', description: '- “I’VE A FEELING WE’RE NOT IN KANSAS ANYMORE.” - Spend the weekend with us in San Francisco! Sightseeing in the city, surfing lessons and more! We’ll pay for two nights at the W Hotel, but you will be responsible for all flights to and from San Francisco. You’ll be credited as a Producer in Stunt Runner, and you’ll also receive four special edition copies of the game (on top of the one received at the $30 tier) and all previous non-limited reward tiers.')
Pledge.create(project_id: p.id, min_amount: 10000, delivery_date: '01.01.2014', description: '- “MADE IT MA! TOP OF THE WORLD!” This is it! You are completely onboard with our vision for Stunt Runner! We will be attending a variety of trade shows to promote the game, and we would like YOU to join us. We will pay the price of your attendance, room, and board (airfare not included) at any show that we attend (minimum of three). Help us show off the game, hang out with other developers, and get a better idea of what our world is like. You’ll receive an “Executive Producer” credit, four special edition copies of the game (on top of the one received at the $30 tier) and all previous non-limited reward tiers. You will also receive a crown made of paper mache and tears of joy!')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-05').id, amount_backers: 2, amount_pledged: 15)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-06').id, amount_backers: 18, amount_pledged: 94)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-07').id, amount_backers: 47, amount_pledged: 256)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-08').id, amount_backers: 52, amount_pledged: 400)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-09').id, amount_backers: 60, amount_pledged: 509)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-10').id, amount_backers: 71, amount_pledged: 734)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-11').id, amount_backers: 85, amount_pledged: 806)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-12').id, amount_backers: 87, amount_pledged: 1258)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-13').id, amount_backers: 89, amount_pledged: 1434)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-14').id, amount_backers: 99, amount_pledged: 1945)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-15').id, amount_backers: 101, amount_pledged: 2431)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-16').id, amount_backers: 117, amount_pledged: 2945)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-17').id, amount_backers: 124, amount_pledged: 3015)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-18').id, amount_backers: 135, amount_pledged: 3415)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 140, amount_pledged: 3947)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 159, amount_pledged: 4319)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 162, amount_pledged: 4579)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 170, amount_pledged: 4663)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 172, amount_pledged: 7435)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 174, amount_pledged: 8765)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 177, amount_pledged: 9957)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 182, amount_pledged: 11051)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 186, amount_pledged: 11101)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 190, amount_pledged: 11234)





p = Project.create(goal: 72000, start_date: '16.07.2013', expiration_date: '26.28.2013', kick_id: 'johnwrot/the-kings-armory-the-tower-defense-board-game', name: 'The King''s Armory -The Tower Defense Board Game! - LAST DAY!', description: 'Strategic Tower Defense Board Game! ~ Free/Low cost Int. Shipping! ~ Co-op or solo! ~ 1 to 7+ players! + Stretch Goals!', project_link: 'http://www.kickstarter.com/projects/johnwrot/the-kings-armory-the-tower-defense-board-game', picture_link: 'https://s3.amazonaws.com/ksr/projects/563984/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/563984/video-280483-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Archived').id)
Pledge.create(project_id: p.id, min_amount: 1, delivery_date: '01.09.2013', description: '"SUPPORTER" - For pledging you will receive: our thanks and eternal gratitude!, entry into our Kickstarter Project Updates for the duration of the campaign, and access to the Print-n-Play files! All greater levels include these rewards.')
Pledge.create(project_id: p.id, min_amount: 7, delivery_date: '01.03.2014', description: '"ALLY" - A hand-made unique and personalized greeting card from the Wrot! Family as a physical sign of our gratitude! Includes Free Shipping to anywhere in the world. (Any pledge level may add $7 to receive such a Thank You!) Includes "Supporter" level.')
Pledge.create(project_id: p.id, min_amount: 49, delivery_date: '01.03.2014', description: '"FOOT SOLDIER!" - One copy of the Game. This, and all higher levels, will include all Unlocked Gamer Achievements (Stretch Goals)! (Saving $25 off of retail, as MSRP is set for $74.99.) AND free U.S. Shipping (...by our Foot Soldiers who work day jobs as mailmen during times of peace.) ~ Add $20 for shipping to Canada (...by our Archers who will tie it to an arrow and shoot it over the border.) ~ Add $15 to this or any Level for a signed copy. ~ Add $45 to this or any order level to add an additional game ($30 savings!)!')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.03.2014', description: '“PSION - Universal International Shipping Option” – 1 copy of the game with International Shipping (…by our Psion who can teleport stuff anywhere he wants). When pledging at this level, please consult the **International Shipping Rates Chart** to the left and *Add Your Appropriate Shipping Cost* to your pledge based on your location.')
Pledge.create(project_id: p.id, min_amount: 59, delivery_date: '01.03.2014', description: '"HERO UPGRADE!" - A Copy of the Game PLUS we will add Asphar the Barbarian to your game! A serious Damage output Hero with the ability to deal damage as either Melee or Supernatural! This is a Kickstarter Exclusive Bonus only available by pledging via Kickstarter! ~ He comes with ALL of the following: His Hero Stat Card, his own blue d20, his own specialized Reinforcement Card to add to your Reinforcement Deck, AND TWO new Equipment Cards (see detailed description to the left for details)! (Add $10 to any higher pledge level to add Asphar and his bonuses!)')
Pledge.create(project_id: p.id, min_amount: 60, delivery_date: '01.03.2014', description: '“PSION - U.I.S.O. - HERO UPGRADE” - A copy of the game PLUS Asphar the Barbarian Hero Upgrade, shipped anywhere in the world! When pledging at this level, please consult the **International Shipping Rates Chart** to the left and *Add Your Appropriate Shipping Cost* to your pledge based on your location.')
Pledge.create(project_id: p.id, min_amount: 64, delivery_date: '01.03.2014', description: '"SPECIAL AID" - Includes: 1) A copy of the Game. 2) The Asphar the Barbarian Hero Upgrade. PLUS 3) the unique "Special Aid" Reinforcement Card! It should be noted that: "Special Aid" is a Limited Edition Reinforcement Card *ONLY* available through this Kickstarter Backing! (Yes you read that right: only 270 copies of this card exist. I have 1, several are reserved for Design and Keepers of the Gate Level pledges below, and the other 197 are for you!!)')
Pledge.create(project_id: p.id, min_amount: 65, delivery_date: '01.03.2014', description: '“PSION - U.I.S.O. - SPECIAL AID” - Includes: 1) A copy of the Game. 2) The Asphar the Barbarian Hero Upgrade. PLUS 3) the unique "Special Aid" Reinforcement Card, shipped to anywhere in the world! When pledging at this level, please consult the **International Shipping Rates Chart** to the left and *Add Your Appropriate Shipping Cost* to your pledge based on your location. ~ Backers in ANY LOCATION (International or USA) may pledge at this level to receive the unique "SPECIAL AID" Reinforcement Card.')
Pledge.create(project_id: p.id, min_amount: 98, delivery_date: '01.03.2014', description: '“MAGE” – 2 copies of the game with all Gamer Achievements, with shipping included, to anywhere in the world (…by our Mage who can teleport himself with a copy in each hand.) ~ Add $20 to add Asphar the Barbarian to both copies. ~ This level is recommended for backers in Asia, Africa, Central & South America, and Australia. When shipping to these countries it works out to only $30 shipping per game ~ A $15 per game savings over buying each individually! ~ Each pledge at this level will count as 2 Backers towards Gamer Achievements.')
Pledge.create(project_id: p.id, min_amount: 140, delivery_date: '01.03.2014', description: '"DESIGN - HIREABLE - MALE" - We will name one of our Hireable Foot Soldiers, Psionicists, or Sorcerers after you (...or your Son or Husband!) in EVERY copy of the game! His name will appear directly on the Hireable''s Spinner Piece! (Male first names only; subject to our discretion.) Full name included in game manual so people know it''s really you. INCLUDES one "Special Aid" copy of the Game.')
Pledge.create(project_id: p.id, min_amount: 140, delivery_date: '01.03.2014', description: '"DESIGN - HIREABLE - FEMALE" - We will name one of our Hireable Archers or Clerics after you (...or your Wife or Daughter!) in EVERY copy of the game! Her name will appear directly on the Hireable''s Spinner Piece! (Female first names only; subject to our discretion.) Full name included in game manual so people know it''s really you. INCLUDES one "Special Aid" copy of the Game.')
Pledge.create(project_id: p.id, min_amount: 210, delivery_date: '01.03.2014', description: '"DESIGN - MONSTERS!" - We will model a Monster image after your likeness (or that of a family member!). And you will get credit in the manual as a supporter and image basis! Also includes a "Special Aid" copy of the game.')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.03.2014', description: '"DESIGN - REINFORCEMENTS!" - YOU are hired as one of the Eccentric King''s Sprite Messengers, sent to call for reinforcements! You may design a brand new Reinforcement Card to be added to every Kickstarter copy of the game! You will invent the idea and suggest an image design, then we will apply the appropriate rules, our artists will render it, and it will be displayed in a Backer Update for all to see when it is complete. Includes credit in the manual as a guest designer! Also includes a "Special Aid" copy of the game, and Free Shipping to anywhere in the world.')
Pledge.create(project_id: p.id, min_amount: 300, delivery_date: '01.03.2014', description: '"DESIGN - ARMORY GNOME!" - You are hired as one of the Eccentric King''s Armory Gnomes! You may design a brand new Armory Card to be added to every Kickstarter copy of the game! You will invent the overpowered creation idea and suggest an image design, then we will apply the appropriate rules, our artists will render it, and it will be displayed in a Backer Update for all to see when it is complete! (2 Only!) Includes credit in the manual as a guest designer! Also includes a "Special Aid" copy of the game, and Free Shipping to anywhere in the world.')
Pledge.create(project_id: p.id, min_amount: 345, delivery_date: '01.03.2014', description: '"DESIGN - BOSS MONSTER!" - Have your likeness rendered as one of our immensely rare monster Bosses to be included in every copy of the game! And you will get credit in the manual as a supporter and image basis! Also includes a "Special Aid" copy of the game, and Free Shipping to anywhere in the world.')
Pledge.create(project_id: p.id, min_amount: 485, delivery_date: '01.03.2014', description: '"TOWER DEFENDER" - Towers are made of brick and mortar and your place of business probably is too. Includes 10 copies of the game teleported (shipped) to anywhere in the world. Add $72 to include 10 Asphar Hero Upgrades (Mega Bonus Deal!) (Group buys ok!) Retailers contact for more info, or 5-buys.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.03.2014', description: '"DESIGN - EPIC HERO!" (Male) - Yeah, you guessed it. There are only 7 Heroes in the base game and YOUR FACE will be on one of them! You will also get credit in the manual as a supporter and image basis! This includes a "Special Aid" copy of the game, and Free Shipping to anywhere in the world.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.03.2014', description: '"DESIGN - EPIC HEROINE!" (Female) - Yuppers, ladies! You get to be rendered as one of the awesome female Heroes! Booyaa! It is our great joy to honor you in this way. And you will get credit in the manual as a supporter and image basis! Includes a "Special Aid" copy of the game, and Free Shipping to anywhere in the world.')
Pledge.create(project_id: p.id, min_amount: 1200, delivery_date: '01.03.2014', description: '"KEEPER OF THE GATE!" - Your family, group of friends, or business associates will rendered by one of our amazing artists in the style of the game art! (Your choice of artist; subject to artist availability.) The image will be included in the manual at half-page size under the special heading of: Keeper of Gate Supporters! This level also includes: 1) a digital copy of the image with rights to reproduce it. 2) A "Special Aid" copy of the game signed by the Creators, including the Authentic "!" and all! 3) A particularly Special Thank You Card. 4) And finally, you gain the right to forever spell your name with an Exclamation Point! ...I mean, that''s just Awesome!')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-16').id, amount_backers: 7, amount_pledged: 234)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-17').id, amount_backers: 13, amount_pledged: 764)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-18').id, amount_backers: 18, amount_pledged: 1697)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-19').id, amount_backers: 25, amount_pledged: 1897)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-20').id, amount_backers: 34, amount_pledged: 1948)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-21').id, amount_backers: 43, amount_pledged: 2159)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-22').id, amount_backers: 52, amount_pledged: 2549)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-23').id, amount_backers: 60, amount_pledged: 2679)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-24').id, amount_backers: 69, amount_pledged: 2794)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-25').id, amount_backers: 74, amount_pledged: 3159)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-26').id, amount_backers: 85, amount_pledged: 3279)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-27').id, amount_backers: 97, amount_pledged: 3489)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-28').id, amount_backers: 114, amount_pledged: 3797)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-29').id, amount_backers: 125, amount_pledged: 4957)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-30').id, amount_backers: 134, amount_pledged: 5768)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-07-31').id, amount_backers: 139, amount_pledged: 6879)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-01').id, amount_backers: 145, amount_pledged: 7586)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-02').id, amount_backers: 155, amount_pledged: 9478)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-03').id, amount_backers: 163, amount_pledged: 10987)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-04').id, amount_backers: 172, amount_pledged: 11897)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-05').id, amount_backers: 185, amount_pledged: 13489)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-06').id, amount_backers: 194, amount_pledged: 13974)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-07').id, amount_backers: 213, amount_pledged: 14598)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-08').id, amount_backers: 229, amount_pledged: 15746)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-09').id, amount_backers: 232, amount_pledged: 15897)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-10').id, amount_backers: 236, amount_pledged: 16484)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-11').id, amount_backers: 245, amount_pledged: 16859)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-12').id, amount_backers: 249, amount_pledged: 17197)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-13').id, amount_backers: 254, amount_pledged: 17987)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-14').id, amount_backers: 264, amount_pledged: 18369)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-15').id, amount_backers: 270, amount_pledged: 18796)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-16').id, amount_backers: 279, amount_pledged: 19639)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-17').id, amount_backers: 280, amount_pledged: 19794)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-18').id, amount_backers: 281, amount_pledged: 20146)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-19').id, amount_backers: 284, amount_pledged: 20987)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 294, amount_pledged: 21547)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 305, amount_pledged: 22148)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 317, amount_pledged: 22569)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 328, amount_pledged: 23473)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 344, amount_pledged: 24075)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 353, amount_pledged: 24677)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 362, amount_pledged: 25279)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 362, amount_pledged: 25279)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 363, amount_pledged: 25283)





c = Category.find_by_description('Photography')





p = Project.create(goal: 15000, start_date: '20.09.2013', expiration_date: '19.10.2013', kick_id: '1016239196/avenue-of-the-strongest', name: 'AVENUE OF THE STRONGEST', description: 'Witness 9/11 through the lens of the closest surviving photographer, Mark Roddenberry.', project_link: 'http://www.kickstarter.com/projects/1016239196/avenue-of-the-strongest', picture_link: 'https://s3.amazonaws.com/ksr/projects/613265/photo-main.jpg', video_link: 'https://www.youtube.com/watch?v=X7wNTnomZGA', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.11.2013', description: 'For your contribution you will receive an electronic copy of the early release book. This will be an e-book PDF.')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.11.2013', description: 'For your contribution you will receive an 8x10 archival print signed by the photographer.')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.12.2013', description: 'For your contribution you''ll receive a beautifully printed limited edition softcover copy of the book.')
Pledge.create(project_id: p.id, min_amount: 200, delivery_date: '01.12.2013', description: 'For your contribution you will receive an elegant hardcover copy of the book with a full color gloss printed dust jacket..')
Pledge.create(project_id: p.id, min_amount: 350, delivery_date: '01.11.2013', description: 'For your contribution you will receive both a signed hardcover copy of the book and two signed 8x10 archival prints from the 9/11 exhibit.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.12.2013', description: 'For your contribution the photographer will give a presentation at your school or organization anywhere in the Los Angeles area. You will also receive a signed hardcover copy of the book and two signed 8x10 archival prints from the 9/11 exhibit.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.12.2013', description: 'For your contribution, the photographer will give a presentation at your school or organization anywhere in the US. You will also receive a signed hardcover copy of the book and two signed 8x10 archival prints from the 9/11 exhibit.')
Pledge.create(project_id: p.id, min_amount: 3500, delivery_date: '01.12.2013', description: 'For your contribution you will receive the complete set of 9/11 photographs custom printed by the photographer for the highest quality. Included is a letter from Mark thanking you for your contribution. The prints will be numbered as a complete set. Genuine leather portfolio housing the prints produced by House of Portfolios in NYC. Prints are 11x14. You will also receive the signed hardcover book.')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 2, amount_pledged: 19)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 7, amount_pledged: 478)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 10, amount_pledged: 512)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 11, amount_pledged: 591)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 13, amount_pledged: 769)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 15, amount_pledged: 843)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 17, amount_pledged: 1077)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 21, amount_pledged: 1154)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 26, amount_pledged: 1234)





p = Project.create(goal: 6000, start_date: '20.09.2013', expiration_date: '19.10.2013', kick_id: 'michaelfriberg/by-the-olive-trees-stories-of-syrian-refugees', name: '"By the Olive Trees": Stories of Syrian Refugees', description: '"By the Olive Trees" is a 64-page color newsprint publication consisting of stories from those affected by the Syrian civil war.', project_link: 'http://www.kickstarter.com/projects/michaelfriberg/by-the-olive-trees-stories-of-syrian-refugees', picture_link: 'https://s3.amazonaws.com/ksr/projects/641252/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/641252/video-280753-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.11.2013', description: 'A copy of the 64-page newsprint publication, as well as your choice of one of two unsigned, open edition 8x10 inch prints from the project. In addition, you will be listed on the back page of the publication as a supporter of the project.')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.11.2013', description: 'A copy of the 64-page newsprint publication, a handwritten thank you note from Michael Friberg and Benjamin Rasmussen, and your choice of one of two unsigned, open edition 11x14 inch prints from the project. In addition, you will be listed on the back page of the publication as a supporter of the project.')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.11.2013', description: 'Your choice of one of two DIY posters, which are 49-piece, 77x60 inch color digitally printed on 70lb paper, as well as a copy of the 64-page newsprint publication. In addition, you will be listed on the back page of the publication as a supporter of the project.')
Pledge.create(project_id: p.id, min_amount: 250, delivery_date: '01.11.2013', description: 'Receive 25 copies of the newspaper to distribute at an event of your choosing. If you live within 50 miles of Salt Lake City or Denver, either Michael Friberg or Benjamin Rasmussen will come to the event and talk about the project. If you don''t live near us, we will Skype in. Be creative! This could be a great way to engage your community with the project. Invite us to your Bunko night, church group, high school class, etc.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.11.2013', description: 'A copy of the 64-page newsprint publication and a 24x30 inch archival pigment print of "Amman at Dusk" by Benjamin Rasmussen, in a limited edition of 5. In addition, you will be listed on the back page of the publication as a supporter of the project.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.11.2013', description: 'A copy of the 64-page newsprint publication and a 24x30 inch archival pigment print of "Outskirts" by Michael Friberg, in a limited edition of 5. In addition, you will be listed on the back page of the publication as a supporter of the project.')
Pledge.create(project_id: p.id, min_amount: 1500, delivery_date: '01.11.2013', description: 'Your name (or your company or publication''s name) will be listed as a sponsor of the project alongside Kodak''s in the beginning of the publication. You will also receive a 40x50 inch archival pigment print of "Shade" by Benjamin Rasmussen, in a limited edition of 3.')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 7, amount_pledged: 247)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 42, amount_pledged: 2479)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 77, amount_pledged: 3459)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 93, amount_pledged: 3868)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 117, amount_pledged: 4695)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 132, amount_pledged: 5367)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 148, amount_pledged: 6120)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 153, amount_pledged: 6281)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 162, amount_pledged: 6457)





p = Project.create(goal: 25000, start_date: '20.09.2013', expiration_date: '19.10.2013', kick_id: '1294097730/tennessee-river-sparkling-gem-of-the-south', name: 'Tennessee River: Sparkling Gem of the South', description: 'Photographer/pilot, Ron Lowery uses his aerial artistry to connect us all environmentally and emotionally to the Tennessee River', project_link: 'http://www.kickstarter.com/projects/1294097730/tennessee-river-sparkling-gem-of-the-south', picture_link: 'https://s3.amazonaws.com/ksr/projects/634130/photo-main.jpg', video_link: 'https://d2pq0u4uni88oo.cloudfront.net/projects/634130/video-278796-h264_high.mp4', category_id: c.id, status_id: Status.find_by_description('Active').id)
Pledge.create(project_id: p.id, min_amount: 5, delivery_date: '01.10.2013', description: 'RAINDROP LEVEL: Every drop counts! A “thank you” and know you are contributing to a wonderful project. Please spread the word to all your friends on email, twitter and facebook. Spreading the word is worth a lot!')
Pledge.create(project_id: p.id, min_amount: 25, delivery_date: '01.10.2013', description: 'BROOK LEVEL: POSTCARDS, Three beautiful, 6’x9” embossed postcards featuring images from the book. Please pass the word out to everyone, your help is very important.')
Pledge.create(project_id: p.id, min_amount: 50, delivery_date: '01.10.2013', description: 'CREEK LEVEL: THE BOOK: a hard-back book with foiled, embossed cover, 144 pages. *Add $50/copy for additional copies.')
Pledge.create(project_id: p.id, min_amount: 75, delivery_date: '01.10.2013', description: 'STREAM LEVEL: THE BOOK, plus three POSTCARDS, Estimated Delivery: Oct. 2013, Shipped anywhere in the United States')
Pledge.create(project_id: p.id, min_amount: 100, delivery_date: '01.10.2013', description: 'TRIBUTARIES LEVEL: A SIGNED BOOK and three POST CARDS, PLUS keepsake BOTTLE OF TENNESSEE RIVER WATER from Mile Marker 477, with custom signed label.')
Pledge.create(project_id: p.id, min_amount: 225, delivery_date: '01.10.2013', description: ' LAKES LEVEL: SIGNED BOOK, 15” signed fine art PRINT of the cover, keepsake BOTTLE OF TENNESSEE RIVER from Mile Marker 477, with custom signed label, and three POST CARDS.')
Pledge.create(project_id: p.id, min_amount: 500, delivery_date: '01.10.2013', description: 'TENNESSEE RIVER LEVEL: A SIGNED BOOK, 15” signed fine art PRINT of the cover, keepsake BOTTLE OF TENNESSEE RIVER water from Mile Marker 477, with custom, signed label, and three POST CARDS and a PERSONAL PHONE CALL where I will answer your questions about the book, the plane, how we did the project, shooting aerials, and advice on your own photography.')
Pledge.create(project_id: p.id, min_amount: 1000, delivery_date: '01.10.2013', description: 'WATERSHED LEVEL: A “watershed” is a signature event to celebrate! This level will thank you for your generosity with a BOOK signed with a PERSONALIZED message for you and a LEATHER SLIPCASE with foiled TITLE on the outside, a 24” signed fine art PRINT of YOUR CHOICE of image from the book, and a PERSONAL PHONE CALL where I will answer your questions about the book, the plane, how we did the project, shooting aerials, and advice on your own photography.')
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-20').id, amount_backers: 2, amount_pledged: 75)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-21').id, amount_backers: 10, amount_pledged: 277)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-22').id, amount_backers: 20, amount_pledged: 948)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-23').id, amount_backers: 27, amount_pledged: 1430)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-24').id, amount_backers: 32, amount_pledged: 1769)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-25').id, amount_backers: 35, amount_pledged: 2139)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-26').id, amount_backers: 40, amount_pledged: 2510)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-27').id, amount_backers: 43, amount_pledged: 2611)
Daily.create(project_id: p.id, push_date_id: PushDate.find_by_push_date('2013-08-28').id, amount_backers: 49, amount_pledged: 2657)